#!/usr/bin/env python3
# Phase 22.1 — the SQLite competitive envelope.
#
# ## Why this file exists
#
# The Phase-16/18/19 equal-contract court measured VOLE against ONE SQLite
# baseline (`tools/fixtures/phase18-contract-packed.py`), which is retained here
# UNMODIFIED as the historical control. That baseline is defensible but is not
# necessarily SQLite's cheapest honest configuration for the workload:
#
#   * it runs `journal_mode=WAL`, `synchronous=NORMAL` (never compared to VOLE's
#     own durability boundary);
#   * it carries TWO full FTS5 indexes (`fts` unicode61 + `fts_tri` trigram) that
#     the C0..C5 contract NEVER exercises (there is no search observation);
#   * its build wall mixes Python orchestration + Poppler extraction with the
#     SQLite write, and it writes rows one `execute()` at a time, no `executemany`,
#     no explicit cache budget;
#   * its storage headline is a point estimate against that one baseline.
#
# So its ~0.96x (median) build ratio and ~0.9x byte ratio are legitimate AGAINST
# THAT BASELINE but are not evidence against the Pareto-optimal SQLite an expert
# would build. This file builds that envelope.
#
# ## The envelope (one lane per configuration; nothing is substituted)
#
#   minimal    source + value/metadata tables, minimal indexing.       cap C0
#   fts        minimal + ONE correctly tuned FTS5 index, external        cap C0
#              content, detail=none, columnsize=0, unicode61 — no
#              trigram (the contract never asks for substring search,
#              so an FTS index is pure overhead here; we quantify it).
#   structural minimal + native coordinates (column + index).           cap C1
#   full       all required contract projections (value, coord,          cap C5
#              provenance, exact closure, revision lineage), NO FTS —
#              i.e. the Phase-16/18 contract without its dead indexes.
#   adaptive   builds minimal and materializes a structure the first     cap C5
#              time a contract depth demands it; ALL cost charged.
#   hybrid     `full` + strongest physical tuning + the native          cap C5
#              (Poppler) extractor path for PDF; see the limitation
#              noted in `build()`.
#
# Every configuration gets: WAL, an explicit `synchronous` (NORMAL or FULL),
# `cache_size`, `temp_store`, `mmap_size`, one transaction per build, and
# `executemany` batching. Durability is a flag so the court can run a MATCHED
# setting for the headline and report the other separately.
#
# ## What this file does NOT do
#
# It does not touch `phase18-contract-packed.py`, any phase-1{6,7,8,9}/
# phase-19/phase-20 court, `real100-v1/`, or `src/`. It creates new files only.
# It writes no wire byte and changes no decode path; exactness stays
# `materialize(descriptor) == original_bytes`.
#
# ## Subcommands
#
#   extract  --format F --source S --out FILE
#   build    --config C --format F --source S --db D --through N [--durability S]
#            [--family ID] [--member ID] [--is-head 0|1] [--extract-json FILE]
#            [--metrics FILE]
#   ensure   --config C --db D --format F --source S --depth N [--family ID]
#            [--member ID] [--is-head 0|1] [--metrics FILE]   (adaptive only)
#   materialize --db D --out FILE
#   sqlgen   --out DIR --depths "0 1 2 3 4 5"     (identical SQL to the control)
#   aggregate RAW CAMPAIGN --reps N ...
#
# The observation SQL is generated by the UNCHANGED historical control
# (`phase18-contract-packed.py::sql_for`), so every competitor's answers are
# byte-comparable with the Phase-18 lane and with VOLE.

import argparse
import hashlib
import importlib.util
import json
import math
import os
import random
import shutil
import sqlite3
import statistics
import sys
import time


# ---------------------------------------------------------------------------
# Delegate extraction + SQL generation + value semantics to the frozen control
# ---------------------------------------------------------------------------

def _load_control():
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, "phase18-contract-packed.py")
    spec = importlib.util.spec_from_file_location("phase18_contract_packed", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


CTRL = _load_control()

# Capability ceiling: the deepest contract depth each configuration covers.
CAP = {
    "minimal": 0,
    "fts": 0,
    "structural": 1,
    "full": 5,
    "adaptive": 5,
    "hybrid": 5,
}

# Required structural depth for each optional projection.
NEED_COORD = 1
NEED_PROV = 2
NEED_EXACT = 3
NEED_REV = 4

ALL_CONFIGS = ["minimal", "fts", "structural", "full", "adaptive", "hybrid"]


def _rm(p):
    for suf in ("", "-wal", "-shm", "-journal"):
        try:
            os.remove(p + suf)
        except FileNotFoundError:
            pass


def _now_us():
    return int(time.monotonic() * 1_000_000)


def _file_bytes(*paths):
    """SUM OF REGULAR-FILE SIZES (ADR-0049). Never `du -sb`."""
    total = 0
    for p in paths:
        try:
            total += os.path.getsize(p)
        except OSError:
            pass
    return total


# ---------------------------------------------------------------------------
# PRAGMA profiles and schema
# ---------------------------------------------------------------------------

def pragmas(config, durability):
    """The durability + performance PRAGMAs, stated explicitly per lane.

    `journal_mode=WAL` is used for every lane so the durability contract is
    comparable: WAL keeps the database *consistent* after a crash but, under
    `synchronous=NORMAL`, may lose the latest committed transactions on certain
    power failures. `synchronous=FULL` removes that exposure at a per-commit
    fsync cost; the court reports both (matched NORMAL for the headline).
    """
    sync = "FULL" if durability == "full" else "NORMAL"
    cache = {"minimal": -2000, "fts": -8000, "structural": -8000}.get(config, -65536)
    mmap = 0 if config == "minimal" else 268435456
    lines = [
        "PRAGMA journal_mode=WAL;",
        "PRAGMA synchronous=%s;" % sync,
        "PRAGMA cache_size=%d;" % cache,
        "PRAGMA temp_store=MEMORY;",
        "PRAGMA mmap_size=%d;" % mmap,
        "PRAGMA foreign_keys=OFF;",
    ]
    if config == "hybrid":
        # Strongest practical tuning: bigger cache + a large WAL journal budget so
        # the single build transaction does not force an in-transaction checkpoint.
        lines.append("PRAGMA cache_size=-131072;")
        lines.append("PRAGMA journal_size_limit=268435456;")
    return "\n".join(lines) + "\n"


def _base_tables():
    return """
CREATE TABLE documents(
  doc_id INTEGER PRIMARY KEY, format TEXT NOT NULL, path TEXT NOT NULL,
  source_len INTEGER NOT NULL, source_sha256 TEXT NOT NULL,
  pages INTEGER, spine INTEGER, doc_text TEXT);
CREATE TABLE blocks(
  block_id INTEGER PRIMARY KEY, doc_id INTEGER NOT NULL, unit TEXT NOT NULL,
  ordering INTEGER NOT NULL, kind TEXT NOT NULL, text TEXT NOT NULL,
  text_sha256 TEXT NOT NULL);
CREATE TABLE headings(
  heading_id INTEGER PRIMARY KEY, doc_id INTEGER NOT NULL, block_id INTEGER NOT NULL,
  level INTEGER NOT NULL, ord INTEGER NOT NULL);
CREATE TABLE db_tables(
  table_id INTEGER PRIMARY KEY, doc_id INTEGER NOT NULL, block_id INTEGER NOT NULL,
  n_rows INTEGER, n_cols INTEGER);
CREATE TABLE table_cells(
  table_id INTEGER NOT NULL, r INTEGER NOT NULL, c INTEGER NOT NULL, text TEXT,
  PRIMARY KEY(table_id, r, c));
CREATE TABLE resources(
  resource_id INTEGER PRIMARY KEY, doc_id INTEGER NOT NULL, path TEXT NOT NULL,
  kind TEXT, member_bytes INTEGER, member_sha256 TEXT);
CREATE TABLE metadata(
  doc_id INTEGER NOT NULL, key TEXT NOT NULL, value TEXT, PRIMARY KEY(doc_id, key));
CREATE TABLE source_blob(doc_id INTEGER PRIMARY KEY, payload BLOB NOT NULL);
"""


def schema(config, effective, tuned_index=True):
    """Schema for `config` built to contract depth `effective`.

    Escalates exactly like the historical control (coord at C1, provenance at C2,
    revision lineage at C4; C3 reuses the retained source blob) so a config's
    build bytes/wall are directly comparable depth by depth. `minimal`/`fts` are
    clamped to C0 by the caller (CAP), so they never grow.
    """
    s = _base_tables()
    if config in ("structural", "full", "hybrid") and effective >= NEED_COORD:
        s += "ALTER TABLE blocks ADD COLUMN native_coord TEXT;\n"
        if tuned_index:
            s += "CREATE INDEX idx_blocks_coord ON blocks(doc_id, native_coord);\n"
        s += "CREATE INDEX idx_blocks_doc ON blocks(doc_id, unit, ordering);\n"
    elif config in ("full", "hybrid") and tuned_index:
        # Full/hybrid keep the doc/unit/ordering index even at C0 (a value lookup
        # index the contract's `text`/`heading` observations use). `minimal` omits
        # it on purpose: that is what "minimal indexing" means and what we charge.
        s += "CREATE INDEX idx_blocks_doc ON blocks(doc_id, unit, ordering);\n"
    if config in ("full", "hybrid") and effective >= NEED_PROV:
        s += """
CREATE TABLE provenance(
  block_id INTEGER PRIMARY KEY, doc_id INTEGER NOT NULL, class TEXT NOT NULL,
  member TEXT, span_start INTEGER, span_end INTEGER, member_len INTEGER);
CREATE INDEX idx_prov_doc ON provenance(doc_id);
"""
    if config in ("full", "hybrid") and effective >= NEED_REV:
        s += """
CREATE TABLE revisions(
  doc_id INTEGER PRIMARY KEY, family_id TEXT, member_id TEXT, is_head INTEGER NOT NULL);
CREATE INDEX idx_rev_family ON revisions(family_id);
"""
    if config == "fts":
        # ONE correctly tuned FTS5 index. External content (no duplicated text),
        # detail=none (document-level only — the cheapest useful FTS), no column
        # size bookkeeping, unicode61 with diacritic folding. NO trigram: the
        # contract has no substring/phrase observation, so a second index of that
        # kind is pure overhead. This lane exists to QUANTIFY that overhead.
        s += ("CREATE VIRTUAL TABLE fts USING fts5(text, content='blocks', "
              "content_rowid='block_id', detail=none, columnsize=0, "
              "tokenize='unicode61 remove_diacritics 2');\n")
    return s


# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------

def build(config, fmt, source, db_path, through, durability="normal",
          family="", member="", is_head=1, extract_json=None, metrics_path=None):
    if config not in CAP:
        raise SystemExit("unknown config %r" % config)
    eff = min(through, CAP[config])
    if config == "adaptive":
        eff = 0  # adaptive starts minimal; `ensure` materializes on demand.

    t0 = _now_us()
    if extract_json:
        with open(extract_json) as f:
            doc = json.load(f)
        load_us = _now_us() - t0
        extract_us = 0
    else:
        doc = CTRL.extract(fmt, source)
        extract_us = _now_us() - t0
        load_us = 0

    _rm(db_path)
    con = sqlite3.connect(db_path)
    con.executescript(pragmas(config, durability))
    con.executescript(schema(config, eff))
    cur = con.cursor()

    m = doc["metadata"]
    cur.execute("INSERT INTO documents VALUES(1,?,?,?,?,?,?,?)",
                (fmt, source, m.get("source_len", 0), m.get("source_sha256", ""),
                 m.get("pages"), m.get("spine"), doc.get("doc_text")))
    cur.executemany("INSERT OR REPLACE INTO metadata VALUES(1,?,?)",
                    [(k, str(v)) for k, v in m.items()])

    blocks = doc["blocks"]
    use_coord = eff >= NEED_COORD
    rows = []
    for i, b in enumerate(blocks):
        if use_coord:
            rows.append((i + 1, 1, b["unit"], b["ordering"], b["kind"], b["text"],
                         CTRL.text_sha(b["text"]), b["native_coord"]))
        else:
            rows.append((i + 1, 1, b["unit"], b["ordering"], b["kind"], b["text"],
                         CTRL.text_sha(b["text"])))
    if use_coord:
        cur.executemany("INSERT INTO blocks VALUES(?,?,?,?,?,?,?,?)", rows)
    else:
        cur.executemany("INSERT INTO blocks VALUES(?,?,?,?,?,?,?)", rows)

    block_ids = {b["ordering"]: i + 1 for i, b in enumerate(blocks)}
    cur.executemany("INSERT INTO headings VALUES(?,1,?,?,?)",
                    [(i + 1, block_ids.get(h["block"], 0), h["level"], i)
                     for i, h in enumerate(doc["headings"])])
    cur.executemany("INSERT INTO db_tables VALUES(?,1,?,?,?)",
                    [(i + 1, block_ids.get(t["block"], 0), t["n_rows"], t["n_cols"])
                     for i, t in enumerate(doc["tables"])])
    cur.executemany("INSERT INTO table_cells VALUES(?,?,?,?)",
                    [(c["table"] + 1, c["r"], c["c"], c["text"]) for c in doc["cells"]])
    cur.executemany("INSERT INTO resources VALUES(?,1,?,?,?,?)",
                    [(i + 1, r["path"], r.get("kind"), r.get("member_bytes"),
                      r.get("member_sha256")) for i, r in enumerate(doc["resources"])])

    if config == "fts":
        cur.execute("INSERT INTO fts(rowid,text) SELECT block_id,text FROM blocks")

    if eff >= NEED_PROV and config in ("full", "hybrid"):
        prow = []
        for i, b in enumerate(blocks):
            sp = b.get("span")
            prow.append((i + 1, 1, b["prov_class"], b.get("prov_member"),
                         sp[0] if sp else None, sp[1] if sp else None, None))
        cur.executemany("INSERT INTO provenance VALUES(?,?,?,?,?,?,?)", prow)

    with open(source, "rb") as f:
        payload = f.read()
    cur.execute("INSERT INTO source_blob VALUES(1,?)", (payload,))

    if eff >= NEED_REV and config in ("full", "hybrid"):
        cur.execute("INSERT INTO revisions VALUES(1,?,?,?)",
                    (family or None, member or os.path.basename(source),
                     1 if is_head else 0))

    con.commit()
    t_db = _now_us()
    con.close()
    close_us = _now_us() - t_db

    db_bytes = _file_bytes(db_path, db_path + "-wal", db_path + "-shm")
    metrics = {
        "config": config, "durability": durability, "through": through,
        "effective": eff, "extract_us": extract_us, "load_us": load_us,
        "db_us": t_db - t0 - load_us - extract_us, "close_us": close_us,
        "db_bytes": db_bytes,
        "blocks": len(blocks), "headings": len(doc["headings"]),
        "tables": len(doc["tables"]), "cells": len(doc["cells"]),
        "resources": len(doc["resources"]),
    }
    if metrics_path:
        with open(metrics_path, "w") as f:
            json.dump(metrics, f, sort_keys=True)
    return metrics


# ---------------------------------------------------------------------------
# Adaptive lazy materialization (ALL cost charged to the first demanding call)
# ---------------------------------------------------------------------------

def _columns(con, table):
    return {r[1] for r in con.execute("PRAGMA table_info(%s)" % table)}


def ensure(config, db_path, fmt, source, depth, family="", member="", is_head=1,
           metrics_path=None):
    """Materialize, on first demand, whatever contract depth `depth` requires.

    Only `adaptive` uses this; other configs are already built for their depth.
    The re-extraction and the DDL/DML are timed together and charged here — this
    is the whole point of the lane (its "learning" is not free).
    """
    if config != "adaptive":
        return {"config": config, "ensure_us": 0, "materialized": []}
    t0 = _now_us()
    con = sqlite3.connect(db_path)
    con.executescript(pragmas(config, "normal"))
    cur = con.cursor()
    matd = []
    need_coord = depth >= NEED_COORD and "native_coord" not in _columns(con, "blocks")
    need_prov = depth >= NEED_PROV and not cur.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name='provenance'").fetchone()
    need_rev = depth >= NEED_REV and not cur.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name='revisions'").fetchone()
    need_index = (depth >= NEED_COORD and not cur.execute(
        "SELECT 1 FROM sqlite_master WHERE type='index' AND name='idx_blocks_doc'").fetchone())
    if not (need_coord or need_prov or need_rev or need_index):
        con.close()
        return {"config": config, "ensure_us": _now_us() - t0, "materialized": []}

    doc = CTRL.extract(fmt, source)
    if need_coord:
        cur.execute("ALTER TABLE blocks ADD COLUMN native_coord TEXT")
        cur.executemany("UPDATE blocks SET native_coord=? WHERE ordering=?",
                        [(b["native_coord"], b["ordering"]) for b in doc["blocks"]])
        cur.execute("CREATE INDEX idx_blocks_coord ON blocks(doc_id, native_coord)")
        matd.append("coord")
    if need_index:
        cur.execute("CREATE INDEX idx_blocks_doc ON blocks(doc_id, unit, ordering)")
        matd.append("idx_blocks_doc")
    if need_prov:
        cur.execute("""
CREATE TABLE provenance(
  block_id INTEGER PRIMARY KEY, doc_id INTEGER NOT NULL, class TEXT NOT NULL,
  member TEXT, span_start INTEGER, span_end INTEGER, member_len INTEGER)""")
        cur.execute("CREATE INDEX idx_prov_doc ON provenance(doc_id)")
        prow = []
        for i, b in enumerate(doc["blocks"]):
            sp = b.get("span")
            prow.append((i + 1, 1, b["prov_class"], b.get("prov_member"),
                         sp[0] if sp else None, sp[1] if sp else None, None))
        cur.executemany("INSERT INTO provenance VALUES(?,?,?,?,?,?,?)", prow)
        matd.append("provenance")
    if need_rev:
        cur.execute("""
CREATE TABLE revisions(
  doc_id INTEGER PRIMARY KEY, family_id TEXT, member_id TEXT, is_head INTEGER NOT NULL)""")
        cur.execute("CREATE INDEX idx_rev_family ON revisions(family_id)")
        cur.execute("INSERT INTO revisions VALUES(1,?,?,?)",
                    (family or None, member or os.path.basename(source),
                     1 if is_head else 0))
        matd.append("revisions")
    con.commit()
    con.close()
    metrics = {"config": config, "depth": depth, "ensure_us": _now_us() - t0,
               "materialized": matd}
    if metrics_path:
        with open(metrics_path, "w") as f:
            json.dump(metrics, f, sort_keys=True)
    return metrics


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv=None):
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)

    e = sub.add_parser("extract")
    e.add_argument("--format", required=True)
    e.add_argument("--source", required=True)
    e.add_argument("--out", required=True)

    b = sub.add_parser("build")
    b.add_argument("--config", required=True)
    b.add_argument("--format", required=True)
    b.add_argument("--source", required=True)
    b.add_argument("--db", required=True)
    b.add_argument("--through", type=int, required=True)
    b.add_argument("--durability", default="normal", choices=["normal", "full"])
    b.add_argument("--family", default="")
    b.add_argument("--member", default="")
    b.add_argument("--is-head", type=int, default=1)
    b.add_argument("--extract-json", default=None)
    b.add_argument("--metrics", default=None)

    en = sub.add_parser("ensure")
    en.add_argument("--config", required=True)
    en.add_argument("--db", required=True)
    en.add_argument("--format", required=True)
    en.add_argument("--source", required=True)
    en.add_argument("--depth", type=int, required=True)
    en.add_argument("--family", default="")
    en.add_argument("--member", default="")
    en.add_argument("--is-head", type=int, default=1)
    en.add_argument("--metrics", default=None)

    m = sub.add_parser("materialize")
    m.add_argument("--db", required=True)
    m.add_argument("--out", required=True)

    sg = sub.add_parser("sqlgen")
    sg.add_argument("--out", required=True)
    sg.add_argument("--depths", default="0 1 2 3 4 5")

    ag = sub.add_parser("aggregate")
    ag.add_argument("raw")
    ag.add_argument("campaign")
    ag.add_argument("--reps", type=int, default=3)
    ag.add_argument("--boot", type=int, default=20000)
    ag.add_argument("--seed", type=int, default=220019)
    ag.add_argument("--tie", type=float, default=0.10)

    ns = ap.parse_args(argv)

    if ns.cmd == "extract":
        doc = CTRL.extract(ns.format, ns.source)
        with open(ns.out, "w") as f:
            json.dump(doc, f, sort_keys=True)
        print(json.dumps({"ok": True, "blocks": len(doc["blocks"])}))
        return 0

    if ns.cmd == "build":
        m = build(ns.config, ns.format, ns.source, ns.db, ns.through, ns.durability,
                  ns.family, ns.member, ns.is_head, ns.extract_json, ns.metrics)
        print(json.dumps(m, sort_keys=True))
        return 0

    if ns.cmd == "ensure":
        m = ensure(ns.config, ns.db, ns.format, ns.source, ns.depth,
                   ns.family, ns.member, ns.is_head, ns.metrics)
        print(json.dumps(m, sort_keys=True))
        return 0

    if ns.cmd == "materialize":
        con = sqlite3.connect(ns.db)
        row = con.execute("SELECT payload FROM source_blob WHERE doc_id=1").fetchone()
        con.close()
        if row is None:
            return 3
        with open(ns.out, "wb") as f:
            f.write(row[0])
        return 0

    if ns.cmd == "sqlgen":
        # Identical SQL to the historical control: the observation queries are a
        # property of the CONTRACT, not of the physical tuning, so every lane is
        # served by the frozen control's `sql_for`.
        depths = [int(x) for x in ns.depths.split()]
        for d in depths:
            dd = os.path.join(ns.out, "C%d" % d)
            os.makedirs(dd, exist_ok=True)
            for fmt in ("pdf", "docx", "epub"):
                for obs in CTRL.FMT_OBS[fmt]:
                    with open(os.path.join(dd, "%s.%s.sql" % (fmt, obs)), "w") as f:
                        f.write(CTRL.sql_for(d, fmt, obs))
        print(json.dumps({"depths": depths}))
        return 0

    if ns.cmd == "aggregate":
        return aggregate(ns.raw, ns.campaign, ns.reps, ns.boot, ns.seed, ns.tie)

    return 2


# ---------------------------------------------------------------------------
# Aggregator + Pareto frontier
# ---------------------------------------------------------------------------

def read_tsv(path):
    if not os.path.exists(path):
        return []
    with open(path) as fh:
        hdr = fh.readline().rstrip("\n").split("\t")
        rows = []
        for line in fh:
            if not line.strip():
                continue
            vals = line.rstrip("\n").split("\t")
            if len(vals) != len(hdr):
                continue
            rows.append(dict(zip(hdr, vals)))
        return rows


def percentile(vals, p):
    v = sorted(float(x) for x in vals)
    if not v:
        return 0.0
    if len(v) == 1:
        return v[0]
    k = (len(v) - 1) * p
    f = math.floor(k)
    c = math.ceil(k)
    if f == c:
        return v[int(k)]
    return v[f] * (c - k) + v[c] * (k - f)


def geomean(vals):
    v = [float(x) for x in vals if float(x) > 0]
    if not v:
        return 0.0
    return math.exp(sum(math.log(x) for x in v) / len(v))


def median(vals):
    v = [float(x) for x in vals]
    return statistics.median(v) if v else 0.0


def _collect(rows):
    """lane -> depth -> id -> rep -> us (rc-0 only)."""
    out = {}
    for r in rows:
        if r.get("rc") != "0":
            continue
        out.setdefault(r["lane"], {}).setdefault(r["depth"], {}).setdefault(
            r["id"], {})[int(r["rep"])] = int(r["us"])
    return out


def _collect_cold(rows):
    out = {}
    for r in rows:
        lane, depth, idv = r["lane"], r["depth"], r["id"]
        rep = int(r["rep"])
        cell = out.setdefault(lane, {}).setdefault(depth, {}).setdefault(idv, {})
        cell[rep] = cell.get(rep, 0) + int(r["us"])
    return out


def _flat(series, lane, depth):
    out = {}
    for idv, repmap in series.get(lane, {}).get(depth, {}).items():
        for rep, us in repmap.items():
            out.setdefault(idv, {})[rep] = us
    return out


def _pair(numer, denom):
    out = {}
    for idv in sorted(set(numer) & set(denom)):
        ratios = []
        for rep in sorted(set(numer[idv]) & set(denom[idv])):
            n, d = numer[idv][rep], denom[idv][rep]
            if d > 0 and n > 0:
                ratios.append(n / d)
        if ratios:
            out[idv] = ratios
    return out


def _boot_ci(by_doc, B, seed):
    rng = random.Random(seed)
    docs = sorted(by_doc.keys())
    if not docs:
        return 0.0, 0.0
    draws = []
    for _ in range(B):
        sample = []
        for _ in range(len(docs)):
            sample.extend(by_doc[rng.choice(docs)])
        draws.append(statistics.median(sample) if sample else 0.0)
    draws.sort()
    lo = draws[max(0, int(0.025 * B) - 1)]
    hi = draws[min(B - 1, int(0.975 * B))]
    return lo, hi


def _dominates(a, b):
    """a dominates b on (build, bytes, cold, warm): <= in all, < in at least one."""
    keys = ("build_ms", "bytes", "cold_ms", "warm_ms")
    le = all(a[k] <= b[k] for k in keys)
    lt = any(a[k] < b[k] for k in keys)
    return le and lt


def aggregate(raw, campaign, reps, boot, seed, tie):
    build = read_tsv(os.path.join(raw, "build_samples.tsv"))
    cold = read_tsv(os.path.join(raw, "cold_samples.tsv"))
    warm = read_tsv(os.path.join(raw, "warm_samples.tsv"))
    exact = read_tsv(os.path.join(raw, "exact.tsv"))
    bytes_rows = read_tsv(os.path.join(raw, "bytes.tsv"))
    env = {}
    try:
        env = json.load(open(os.path.join(raw, "environment.json")))
    except (OSError, ValueError):
        pass

    build_s = _collect(build)
    warm_s = _collect(warm)
    cold_s = _collect_cold(cold)

    ids = sorted({r["id"] for r in build})
    lanes = sorted({r["lane"] for r in build})
    sq_lanes = [l for l in lanes if l not in ("vole", "extract")]
    sq_lanes = [l for l in ("minimal", "fts", "structural", "full", "adaptive",
                            "hybrid", "hist") if l in lanes]

    def dep_series(kind, lane):
        return {"build": build_s, "warm": warm_s, "cold": cold_s}[kind].get(lane, {})

    def depths_for(lane):
        ds = {r["depth"] for r in build if r["lane"] == lane and r["rc"] == "0"}
        return sorted(ds, key=lambda x: (x != "all", int(x) if x.isdigit() else 0))

    # ---- persistent bytes (deterministic; sum over docs) -------------------
    bmap = {}       # lane -> depth -> id -> bytes
    fmap = {}       # lane -> depth -> id -> files
    for r in bytes_rows:
        bmap.setdefault(r["lane"], {}).setdefault(r["depth"], {})[r["id"]] = int(r["bytes"])
        fmap.setdefault(r["lane"], {}).setdefault(r["depth"], {})[r["id"]] = int(r["files"])
    bytes_by = {lane: {dep: sum(d.values()) for dep, d in dd.items()}
                for lane, dd in bmap.items()}
    files_by = {lane: {dep: sum(d.values()) for dep, d in dd.items()}
                for lane, dd in fmap.items()}

    # ---- per (lane, depth) pooled medians ---------------------------------
    def pooled(kind, lane, dep):
        s = dep_series(kind, lane).get(dep, {})
        vals = [v for repmap in s.values() for v in repmap.values()]
        return median(vals), geomean(vals), (statistics.stdev(vals) if len(vals) > 1 else 0.0)

    L = []
    A = L.append
    A("# Phase 22.1 — SQLite competitive envelope (equal-contract court)")
    A("")
    A("The historical control (`tools/fixtures/phase18-contract-packed.py`, with "
      "`journal_mode=WAL`, `synchronous=NORMAL`, and TWO full FTS5 indexes) is "
      "retained as a HISTORICAL CONTROL lane (`hist`). The envelope adds six "
      "purpose-tuned configurations. Same 12-document subset, same contract "
      "depths C0–C5, same answer SQL (the frozen control's `sql_for`), same "
      "accounting (persistent bytes = **sum of regular-file sizes**; `du -sb` is "
      "never used). Wall times are integer microseconds; `N={}` repetitions, "
      "paired and interleaved.".format(reps))
    A("")
    A("- documents: **{}**".format(", ".join(ids)))
    A("- paired-ratio estimator: per (doc, rep) VOLE/lane ratio; median + "
      "geometric mean; fixed-seed cluster bootstrap 95% CI over documents "
      "(`{}` resamples, seed {}); ±{:.0f}% per-document tie band.".format(
          boot, seed, 100 * tie))
    A("- configurations: `minimal`, `fts`, `structural`, `full`, `adaptive`, "
      "`hybrid`; historical control `hist`. Capability ceilings: " +
      ", ".join("`{}`≤C{}".format(c, CAP[c]) for c in ALL_CONFIGS) + ".")
    A("")

    # ---- build decomposition ---------------------------------------------
    A("## Build decomposition (extraction vs SQLite write)")
    A("")
    A("Each lane's build is a SINGLE process that extracts and writes (comparable "
      "to VOLE's native build and to the historical control). The shared "
      "Python+Poppler extraction is additionally measured once per (doc, rep) and "
      "shown as the `extract` column; `db` is the lane's process wall minus that "
      "shared extraction (it still contains the interpreter start-up and the DB "
      "write). VOLE has no separate extract column: its build is native.")
    A("")
    A("| lane | depth | extract med ms | db med ms | total med ms | bytes | files |")
    A("|---|---:|---:|---:|---:|---:|---:|")
    ex_rows = [r for r in build if r["lane"] == "extract" and r["rc"] == "0"]
    ex_med = median([int(r["us"]) for r in ex_rows]) if ex_rows else 0
    for lane in ["vole"] + sq_lanes:
        for dep in depths_for(lane):
            s = dep_series("build", lane).get(dep, {})
            dbv = [v for repmap in s.values() for v in repmap.values()]
            if not dbv:
                continue
            if lane == "vole":
                extr = 0
                dbmed = median(dbv)
            else:
                extr = ex_med
                dbmed = max(0, median(dbv) - ex_med)
            b = bytes_by.get(lane, {}).get(dep)
            f = files_by.get(lane, {}).get(dep)
            A("| {} | {} | {:.0f} | {:.0f} | {:.0f} | {} | {} |".format(
                lane, ("C%s" % dep) if dep.isdigit() else dep, extr / 1000, dbmed / 1000,
                (extr + dbmed) / 1000, b if b is not None else "-", f if f is not None else "-"))
    A("")
    A("`extract med` is the shared, separately-measured extraction; each SQLite "
      "lane's build wall in `raw/build_samples.tsv` is a single extract+write "
      "process, so `db med` = wall − `extract med` (floor 0). `extract med` also "
      "carries one Python interpreter start-up; the SQLite lanes' walls carry "
      "another, which an integrated native loader would amortize — an "
      "implementation cost of the Python-orchestrated competitor, stated not "
      "hidden.")
    A("")

    # ---- coverage ---------------------------------------------------------
    A("## Capability coverage (the gate: no omitted competitor capability)")
    A("")
    A("| lane | " + " | ".join("C%d" % d for d in range(6)) + " |")
    A("|---|" + "---|" * 6)
    cov = {"vole": {d: True for d in range(6)}}
    for c in ALL_CONFIGS:
        cov[c] = {d: d <= CAP[c] for d in range(6)}
    if "hist" in lanes:
        cov["hist"] = {d: True for d in range(6)}
    for lane in ["vole"] + sq_lanes:
        A("| {} | ".format(lane) + " | ".join(
            "yes" if cov.get(lane, {}).get(d) else "NO" for d in range(6)) + " |")
    A("")
    A("`minimal`/`fts` cover only C0; `structural` covers C0–C1; `full`/`adaptive`/"
      "`hybrid`/`hist`/VOLE cover the full C0–C5 contract. A configuration is "
      "only compared at a depth it actually covers.")
    A("")

    # ---- frontier ---------------------------------------------------------
    frontier_rows = {}   # depth -> {lane: metrics}
    for dep in range(6):
        for lane in ["vole"] + sq_lanes:
            if not cov.get(lane, {}).get(dep):
                continue
            ds = str(dep)
            bdep = "all" if lane == "vole" else ds
            bv = [v for repmap in dep_series("build", lane).get(bdep, {}).values()
                  for v in repmap.values()]
            cv = [v for repmap in dep_series("cold", lane).get(ds, {}).values()
                  for v in repmap.values()]
            wv = [v for repmap in dep_series("warm", lane).get(ds, {}).values()
                  for v in repmap.values()]
            if not bv or not wv:
                continue
            byt = bytes_by.get(lane, {}).get(ds)
            frontier_rows.setdefault(dep, {})[lane] = {
                "build_ms": median(bv) / 1000,
                "bytes": byt if byt is not None else 0,
                "cold_ms": median(cv) / 1000,
                "warm_ms": median(wv) / 1000,
            }

    A("## Pareto frontier — build / persistent bytes / cold / warm")
    A("")
    A("Each cell is the pooled median over documents×reps (cold = sum of the "
      "per-observation process walls per rep; warm = the one-session batch). "
      "`*` marks Pareto-optimal points within a depth across (build, bytes, cold, "
      "warm); a point is dominated if another is ≤ in every axis and < in one.")
    A("")
    for dep in range(6):
        rows = frontier_rows.get(dep, {})
        if not rows:
            continue
        names = sorted(rows.keys(), key=lambda x: rows[x]["build_ms"])
        pareto = set()
        for a in names:
            if not any(_dominates(rows[b], rows[a]) for b in names if b != a):
                pareto.add(a)
        A("### C{}".format(dep))
        A("")
        A("| lane | build ms | bytes | cold ms | warm ms | pareto |")
        A("|---|---:|---:|---:|---:|:--:|")
        for a in names:
            r = rows[a]
            A("| {}{} | {:.1f} | {} | {:.2f} | {:.2f} | {} |".format(
                a, "", r["build_ms"], r["bytes"], r["cold_ms"], r["warm_ms"],
                "*" if a in pareto else ""))
        A("")
        vole = rows.get("vole")
        if vole:
            for a in names:
                if a == "vole":
                    continue
                r = rows[a]
                wins = []
                for k in ("build_ms", "bytes", "cold_ms", "warm_ms"):
                    if vole[k] < r[k]:
                        wins.append(k)
                    elif r[k] < vole[k]:
                        wins.append("-" + k)
                A("- VOLE vs `{}`: ".format(a) + ", ".join(wins) if wins else
                  "- VOLE vs `{}`: equal".format(a))
        A("")

    # ---- paired VOLE vs each lane, per depth ------------------------------
    A("## Paired VOLE/lane ratios (metric < 1 favours VOLE)")
    A("")
    A("| depth | lane | n docs | build med (CI) | cold med (CI) | warm med (CI) | bytes ratio |")
    A("|---|---|---:|---|---|---|---:|")
    for dep in range(6):
        for lane in sq_lanes:
            if not cov.get(lane, {}).get(dep):
                continue
            ds = str(dep)
            b = _pair(_flat(build_s, "vole", "all"), _flat(build_s, lane, ds))
            c = _pair(_flat(cold_s, "vole", ds), _flat(cold_s, lane, ds))
            w = _pair(_flat(warm_s, "vole", ds), _flat(warm_s, lane, ds))
            if not b and not w:
                continue
            bm = median([r for x in b.values() for r in x]) if b else 0.0
            blo, bhi = _boot_ci(b, boot, seed) if b else (0, 0)
            cm = median([r for x in c.values() for r in x]) if c else 0.0
            clo, chi = _boot_ci(c, boot, seed) if c else (0, 0)
            wm = median([r for x in w.values() for r in x]) if w else 0.0
            wlo, whi = _boot_ci(w, boot, seed) if w else (0, 0)
            vb = bytes_by.get("vole", {}).get(ds)
            lb = bytes_by.get(lane, {}).get(ds)
            br = (vb / lb) if (vb and lb) else 0.0
            A("| C{} | {} | {} | {:.3f} ({:.3f}..{:.3f}) | {:.3f} ({:.3f}..{:.3f}) | "
              "{:.3f} ({:.3f}..{:.3f}) | {:.3f} |".format(
                  dep, lane, len(b), bm, blo, bhi, cm, clo, chi, wm, wlo, whi, br))
    A("")

    # ---- durability FULL cost --------------------------------------------
    dur = read_tsv(os.path.join(raw, "durability.tsv"))
    if dur:
        A("## `synchronous=FULL` cost (measured, reported separately)")
        A("")
        A("Matched-setup builds are `synchronous=NORMAL`. This is the SAME build "
          "at `synchronous=FULL` (per-commit WAL `fsync`), for the `full` C5 "
          "configuration.")
        A("")
        A("| id | NORMAL db ms | FULL db ms | ratio | bytes NORMAL | bytes FULL |")
        A("|---|---:|---:|---:|---:|---:|")
        nb = {r["id"]: r for r in dur if r["durability"] == "normal"}
        fb = {r["id"]: r for r in dur if r["durability"] == "full"}
        for i in sorted(set(nb) & set(fb)):
            n0, f0 = int(nb[i]["db_us"]), int(fb[i]["db_us"])
            A("| {} | {:.1f} | {:.1f} | {:.2f} | {} | {} |".format(
                i, n0 / 1000, f0 / 1000, (f0 / n0 if n0 else 0),
                nb[i]["bytes"], fb[i]["bytes"]))
        A("")

    # ---- exactness --------------------------------------------------------
    A("## Exact original closure (length + SHA-256 + byte compare)")
    A("")
    A("| id | fmt | VOLE ok | control ok | competitors ok |")
    A("|---|---|:--:|:--:|:--:|")
    byid = {}
    fmt_by_id = {}
    for r in exact:
        byid.setdefault(r["id"], {})[r["lane"]] = r["ok"]
        fmt_by_id[r["id"]] = r["fmt"]
    for i in ids:
        m = byid.get(i, {})
        comp = [v for k, v in m.items() if k not in ("vole", "hist")]
        A("| {} | {} | {} | {} | {}/{} |".format(
            i, fmt_by_id.get(i, m.get("fmt", "")), m.get("vole", "?"), m.get("hist", "?"),
            sum(1 for v in comp if v == "1"), len(comp)))
    A("")

    # ---- answer equivalence ----------------------------------------------
    envdir = os.path.join(raw, "env")
    fmt_of = {r["id"]: r["fmt"] for r in bytes_rows}
    fmt_of.update({r["id"]: r["fmt"] for r in build})
    lanes_env = [l for l in (["vole"] + sq_lanes) if l in lanes]
    A("## Answer equivalence (frozen control + VOLE vs every configuration)")
    A("")
    A("On the final repetition every lane's envelope for each (depth, fmt, "
      "observation) is retained under `raw/env/`. Because every SQLite lane is "
      "served by the SAME frozen `sql_for`, a configuration that carries the "
      "same capability must emit a **byte-identical** envelope to the `full` "
      "reference at the same depth (the historical `hist` control is compared "
      "where it was run, C0/C5). VOLE is compared field-by-field with the "
      "reference's `_equiv` (raw / projected / shape / divergent / mismatch).")
    A("")
    A("| lane | depth | envelopes | identical to `full` | VOLE-equiv raw/proj | shape/decline | divergent | mismatch |")
    A("|---|---:|---:|---:|---:|---:|---:|---:|")
    tot_ident = 0
    tot_env = 0
    tot_mm = 0
    tot_div = 0
    for lane in sq_lanes:
        for dep in depths_for(lane):
            n = ident = 0
            vm_raw = vm_shape = vm_div = bad = 0
            for i in ids:
                f = fmt_of.get(i)
                if not f:
                    continue
                for obs in CTRL.FMT_OBS[f]:
                    ctrl_p = os.path.join(envdir, "C%s" % dep,
                                          "%s.%s.%s.full.json" % (i, f, obs))
                    lp = os.path.join(envdir, "C%s" % dep,
                                      "%s.%s.%s.%s.json" % (i, f, obs, lane))
                    if not (os.path.exists(ctrl_p) and os.path.exists(lp)):
                        continue
                    n += 1
                    tot_env += 1
                    if open(ctrl_p, "rb").read() == open(lp, "rb").read():
                        ident += 1
                        tot_ident += 1
                    vp = os.path.join(envdir, "C%s" % dep,
                                      "%s.%s.%s.vole.json" % (i, f, obs))
                    if not os.path.exists(vp):
                        continue
                    try:
                        # an empty file is a typed decline (rc 6 unsupported), not
                        # a value mismatch.
                        if os.path.getsize(vp) == 0:
                            v = {"obs": obs, "declined": True,
                                 "reason": "unsupported"}
                        else:
                            v = CTRL._normalize_vole_answer(
                                json.load(open(vp)), f, obs, int(dep))
                        s = json.load(open(lp))
                        res, _d = CTRL._equiv(int(dep), f, obs, v, s)
                    except (OSError, ValueError):
                        res = "mismatch"
                    if res in ("raw", "projected"):
                        vm_raw += 1
                    elif res in ("shape", "decline", "observable", "capability"):
                        vm_shape += 1
                    elif res == "divergent":
                        vm_div += 1
                        tot_div += 1
                    else:
                        bad += 1
                        tot_mm += 1
            A("| {} | C{} | {} | {}/{} | {} | {} | {} | {} |".format(
                lane, dep, n, ident, n, vm_raw, vm_shape, vm_div, bad))
    A("")
    A("Across all compared cells: **{}/{}** configuration envelopes are "
      "byte-identical to the `full` reference; **{}** VOLE/comparison "
      "mismatches; **{}** are reported as `divergent` (PDF page text is an "
      "independent heuristic projection — VOLE's own parser vs Poppler — and is "
      "never counted as a contract failure).".format(
          tot_ident, tot_env, tot_mm, tot_div))
    A("")

    # ---- durability -------------------------------------------------------
    A("## Durability contracts (compared explicitly, not assumed equal)")
    A("")
    A("**SQLite `journal_mode=WAL`, `synchronous=NORMAL`** (the matched setting "
      "for the headline, matching VOLE's unproven power-loss boundary): the WAL "
      "keeps the database *internally consistent* after a crash, but SQLite "
      "documents that under certain power failures the **latest committed "
      "transactions may be lost**. There is no torn page and no corruption; the "
      "committed prefix is recoverable. `synchronous=FULL` would `fsync` the WAL "
      "on every commit (removing that exposure) at a per-commit latency cost; "
      "the `--durability full` variant of this fixture measures that cost and is "
      "reported separately in `raw/durability_full.*`.")
    A("")
    A("**VOLE packed store (ADR-0053; Phase 20.1)** with `SyncPolicy::Batch` "
      "(the default): records are forced to stable storage once per segment "
      "(seal/flush), the field manifest is **flushed before it is published**, "
      "and recovery is a strict **prefix** — no partial node is ever fetchable "
      "and every node is re-hashed against its id. A crash can therefore lose "
      "records appended since the last flush, but a published manifest is always "
      "consistent. Phase 20.1's 1,300-case fault-injection court passed under "
      "both policies with **zero** bad-hash and **zero** prefix violations, but "
      "it injects process death (`SIGKILL`/`abort`), which leaves the OS page "
      "cache intact: **no `fsync` boundary is actually exercised**, so true "
      "power loss and torn/lost rename remain **argued, not measured**.")
    A("")
    A("**Net.** Both sides at the matched setting can lose the tail of the most "
      "recent writes after a power failure; both preserve consistency and never "
      "expose a partial record. Neither side has a measured true-power-loss "
      "receipt. SQLite `synchronous=FULL` is the stronger, slower option; VOLE's "
      "`--sync=each` (per-record `fdatasync`) is its analogue and was also not "
      "measured under true power loss.")
    A("")

    # ---- answers ----------------------------------------------------------
    A("## Answers")
    A("")
    for dep in range(6):
        rows = frontier_rows.get(dep, {})
        if not rows or "vole" not in rows:
            continue
        v = rows["vole"]
        stronger = []
        for a, r in rows.items():
            if a == "vole":
                continue
            if r["build_ms"] <= v["build_ms"]:
                stronger.append((a, "build"))
            if r["bytes"] and r["bytes"] <= v["bytes"]:
                stronger.append((a, "bytes"))
            if r["warm_ms"] <= v["warm_ms"]:
                stronger.append((a, "warm"))
        if stronger:
            A("- **C{}**: configurations at least matching VOLE — ".format(dep) +
              "; ".join("`{}`≤VOLE on {}".format(a, k) for a, k in stronger) + ".")
        else:
            A("- **C{}**: VOLE is best-or-equal on every axis vs the covering "
              "configurations.".format(dep))
    A("")

    A("## Caveats and honesty")
    A("")
    A("- The store is the bind-mounted `/work`; per-cell CV is in "
      "`raw/per_doc_lane_depth.csv`. Wide intervals are reported wide.")
    A("- `full`/`hybrid` exclude FTS because the contract has **no search "
      "observation**; `hist` carries the control's two FTS indexes and `fts` "
      "carries one tuned index, so the FTS overhead is quantified, not hidden.")
    A("- `hybrid`'s 'native parser/cache' is Poppler (PDF) + Python stdlib "
      "(OOXML/EPUB) — the strongest native extraction available in the pinned "
      "image without modifying `src/`; it is NOT a rewrite of VOLE's adapters.")
    A("- Cells are pooled medians; the paired per-rep CI is the estimator for "
      "ratio claims (ADR-0054). `hist` is measured only at C0 and C5 as a "
      "control point, not at every depth.")
    A("- `adaptive`'s cold column is large at deeper depths **by construction**: "
      "its lazy materialization is charged to the first cold call at each depth "
      "(`raw/cold_samples.tsv` `obs=ensure`), whereas `full`/`hybrid`/`hist` "
      "paid that cost at build. Its warm session and its bytes are the honest "
      "after-materialization numbers.")
    A("")

    report = "\n".join(L)
    with open(os.path.join(campaign, "SUMMARY.md"), "w") as f:
        f.write(report)

    # ---- FRONTIER.md ------------------------------------------------------
    F = []
    F.append("# Phase 22.1 — Pareto frontier (VOLE vs the SQLite envelope)")
    F.append("")
    F.append("Per depth, the covering configurations' pooled medians. `bytes` is "
             "the sum over the 12 documents of regular-file bytes.")
    F.append("")
    for dep in range(6):
        rows = frontier_rows.get(dep, {})
        if not rows:
            continue
        names = sorted(rows.keys(), key=lambda x: rows[x]["build_ms"])
        pareto = set(a for a in names
                     if not any(_dominates(rows[b], rows[a]) for b in names if b != a))
        F.append("## C{}".format(dep))
        F.append("")
        F.append("| lane | build ms | bytes | cold ms | warm ms | Pareto |")
        F.append("|---|---:|---:|---:|---:|:--:|")
        for a in names:
            r = rows[a]
            F.append("| {} | {:.1f} | {} | {:.2f} | {:.2f} | {} |".format(
                a, r["build_ms"], r["bytes"], r["cold_ms"], r["warm_ms"],
                "yes" if a in pareto else ""))
        F.append("")
    frontier = "\n".join(F)
    with open(os.path.join(campaign, "FRONTIER.md"), "w") as f:
        f.write(frontier)

    # per-doc CSV
    with open(os.path.join(raw, "per_doc_lane_depth.csv"), "w") as fh:
        fh.write("kind,id,lane,depth,n,median_ms,mean_ms,min_ms,max_ms,cv\n")
        for kind in ("build", "warm", "cold"):
            series = {"build": build_s, "warm": warm_s, "cold": cold_s}[kind]
            for lane in ["vole"] + sq_lanes:
                for dep, byid in series.get(lane, {}).items():
                    for idv in ids:
                        repmap = byid.get(idv)
                        if not repmap:
                            continue
                        v = [x / 1000.0 for x in repmap.values()]
                        mean = statistics.fmean(v)
                        sd = statistics.stdev(v) if len(v) > 1 else 0.0
                        fh.write("{},{},{},{},{},{:.3f},{:.3f},{:.3f},{:.3f},{:.4f}\n".format(
                            kind, idv, lane, dep, len(v), statistics.median(v), mean,
                            min(v), max(v), sd / mean if mean else 0.0))

    print(report)
    return 0


if __name__ == "__main__":
    sys.exit(main())
