#!/usr/bin/env python3
"""Phase 22.4 (P3) — pre-registered, seeded hidden query schedule.

## Why this file exists

Phase 22.4 asks which system wins the **cumulative lifetime frontier per
equivalent successful observation** on a schedule the encoder never saw. The
schedule must therefore be *frozen before* any measurement, deterministic given a
seed, and its proportions must **not** be tuned to favour either system.

This file produces that schedule. It is deliberately tiny and has no dependence on
VOLE or SQLite: it emits (a) a VOLE `observe-batch` request file (`--requests`) and
(b) the concatenated SQLite statements for the same schedule at each contract
depth, both derived from the *frozen* Phase-18 `sql_for` SQL generated by
`tools/fixtures/phase22-competitors.py sqlgen`.

## The pre-registered schedule recipe (frozen; do not tune)

Vocabulary = the contract observations the format supports (the Phase-18
`FMT_OBS` sets, verbatim):

    pdf   bytes text metadata revision
    docx  bytes text doc-text heading table resource metadata revision
    epub  bytes text doc-text heading table resource metadata revision

For document ``doc_id`` with global seed ``S`` and format ``fmt``:

  1. a **per-document** RNG is seeded from
     ``sha256("phase22-4|<S>|<doc_id>|<fmt>")`` (stable across Python versions);
  2. **proportions are undisclosed and not tuned**: each vocabulary word gets an
     independent weight drawn ``Uniform(0.5, 2.0)`` from that RNG;
  3. **coverage is guaranteed**: the schedule starts with exactly one copy of
     every vocabulary word (in a seeded shuffle), then the remaining
     ``length - |vocab|`` slots are drawn i.i.d. with those weights;
  4. the whole sequence is seeded-shuffled once more.

The recipe is fixed by this docstring and by the recorded seed; changing it would
change the frozen schedule and must be recorded as a new pre-registration.

## Subcommands

    gen --seed S --id DOC --format FMT --length L --out DIR
        [--sqldir DIR --depths "0 1 2 3 4 5"]
        [--vocab "a b c"]

writes ``DIR/<id>.schedule.json`` and ``DIR/<id>.vole.reqs``; with ``--sqldir``
(and ``--depths``) it also writes ``DIR/<id>.sched.C<d>.sql`` for every depth.
Everything is printed to stdout as one JSON object for the court to record.
"""

import argparse
import bisect
import hashlib
import json
import os
import random
import sys


# The contract vocabulary per format. Kept byte-identical to the frozen Phase-18
# ``FMT_OBS`` (phase18-contract-packed.py) and the Phase-22.2 court's ``obs_for``.
VOCAB = {
    "pdf": ["bytes", "text", "metadata", "revision"],
    "docx": ["bytes", "text", "doc-text", "heading", "table", "resource",
             "metadata", "revision"],
    "epub": ["bytes", "text", "doc-text", "heading", "table", "resource",
             "metadata", "revision"],
}

# The VOLE request line for each observation. Kept byte-identical to the frozen
# Phase-18/20/22.2 courts' ``vole_args`` so the VOLE lane sees the same request
# the contract SQL describes.
VOLE_ARGS = {
    "bytes": "--byte-range 0..64 --kind exact",
    "text_pdf": "--page 1 --kind text",
    "text": "--block 0 --kind text",
    "doc-text": "--doc-text --kind text",
    "heading": "--heading 0 --kind text",
    "table": "--table 0 --kind text",
    "resource": "--resource 0 --kind metadata",
    "metadata": "--metadata --kind metadata",
    "revision": "--revisions --kind lineage",
}


def vole_line(fmt, obs):
    if obs == "text" and fmt == "pdf":
        return VOLE_ARGS["text_pdf"]
    return VOLE_ARGS[obs]


def _rng(seed, doc_id, fmt):
    h = hashlib.sha256(
        ("phase22-4|%d|%s|%s" % (seed, doc_id, fmt)).encode("utf-8")).digest()
    return random.Random(int.from_bytes(h, "big"))


def build_schedule(seed, doc_id, fmt, length, vocab=None):
    """Deterministic schedule + the drawn weights (recorded for auditability)."""
    vocab = list(vocab) if vocab else list(VOCAB[fmt])
    if length < len(vocab):
        raise SystemExit("length %d < vocabulary %d" % (length, len(vocab)))
    rng = _rng(seed, doc_id, fmt)
    weights = [rng.uniform(0.5, 2.0) for _ in vocab]
    seq = list(vocab)
    rng.shuffle(seq)
    cum = []
    s = 0.0
    for w in weights:
        s += w
        cum.append(s)
    while len(seq) < length:
        x = rng.random() * s
        i = bisect.bisect_left(cum, x)
        if i >= len(vocab):
            i = len(vocab) - 1
        seq.append(vocab[i])
    rng.shuffle(seq)
    counts = {o: seq.count(o) for o in vocab}
    return seq, weights, counts


def main(argv=None):
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    g = sub.add_parser("gen")
    g.add_argument("--seed", type=int, required=True)
    g.add_argument("--id", required=True)
    g.add_argument("--format", required=True, choices=sorted(VOCAB))
    g.add_argument("--length", type=int, default=24)
    g.add_argument("--out", required=True)
    g.add_argument("--sqldir", default=None)
    g.add_argument("--depths", default="0 1 2 3 4 5")
    g.add_argument("--vocab", default=None,
                   help="override vocabulary (space-separated); default = FMT_OBS")
    ns = ap.parse_args(argv)

    if ns.cmd != "gen":
        return 2

    vocab = ns.vocab.split() if ns.vocab else None
    seq, weights, counts = build_schedule(
        ns.seed, ns.id, ns.format, ns.length, vocab)
    vocab_used = list(vocab) if vocab else list(VOCAB[ns.format])

    os.makedirs(ns.out, exist_ok=True)

    manifest = {
        "phase": "22.4",
        "recipe": "phase22-4-schedule.py gen (frozen recipe in the module docstring)",
        "seed": ns.seed,
        "doc_id": ns.id,
        "format": ns.format,
        "length": ns.length,
        "vocabulary": vocab_used,
        "weights": {o: round(w, 6) for o, w in zip(vocab_used, weights)},
        "counts": counts,
        "schedule": seq,
    }
    with open(os.path.join(ns.out, ns.id + ".schedule.json"), "w") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")

    reqs = [vole_line(ns.format, obs) for obs in seq]
    with open(os.path.join(ns.out, ns.id + ".vole.reqs"), "w") as f:
        f.write("\n".join(reqs) + "\n")

    depths = [int(x) for x in ns.depths.split()] if ns.sqldir else []
    if ns.sqldir:
        for d in depths:
            parts = []
            for obs in seq:
                sqlf = os.path.join(ns.sqldir, "C%d" % d,
                                    "%s.%s.sql" % (ns.format, obs))
                with open(sqlf) as f:
                    parts.append(f.read().strip())
            with open(os.path.join(ns.out, "%s.sched.C%d.sql" % (ns.id, d)), "w") as f:
                f.write(";\n".join(parts) + ";\n")

    print(json.dumps({
        "doc_id": ns.id, "format": ns.format, "seed": ns.seed,
        "length": ns.length, "counts": counts, "schedule": seq,
        "depths": depths,
    }, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
