#!/usr/bin/env bash
# Phase 22.4 (review item P3) — the UNKNOWN-QUERY LIFETIME court.
#
# ## Question
#
#   On a query schedule the encoder never saw, which system wins the **cumulative
#   lifetime frontier per equivalent successful observation**? Both systems see the
#   same documents and choose their representation (Stage A); a **hidden**,
#   pre-registered schedule is then revealed in undisclosed proportions (Stage B);
#   both may adapt and **every** adaptation / storage-growth / read cost is charged
#   (Stage C); the cumulative cost/capability frontier is compared region by region
#   (Stage D).
#
# ## Binding prior (stated, not assumed)
#
#   The Phase-15.6 adaptive-promotion experiment LOST (ADR-0046). A VOLE win here is
#   NOT presumed likely; the pre-registered expectation is "no advantage outside a
#   narrowly characterized region, if any". A loss is a valid result.
#
# ## Method (frozen for this court)
#
#   * The SAME 12-document `real100-v1` subset (4 pdf / 4 docx / 4 epub) as Phase
#     18/19/20/22.2, the same subset.tsv generator, the same accounting
#     (persistent bytes = sum of regular-file sizes; `du -sb` never used),
#     and the same contract SQL (`sql_for`, delegated to the frozen Phase-18
#     control), so only the *schedule* differs from the earlier courts.
#   * The hidden schedule is generated by `tools/fixtures/phase22-4-schedule.py`
#     from a recorded global seed (`SCHED_SEED`) and a per-document seed
#     (`sha256("phase22-4|<seed>|<id>|<fmt>")`); the exact sequence and the drawn
#     weights are written to `raw/sched/<id>.schedule.json` and are frozen. The
#     proportions are a fixed pre-registered random mix, never tuned to VOLE.
#   * Lanes (all under one predeclared capability budget = the contract ceiling C5):
#       vole      `field-build --profile runtime --packed` (the shipping form)
#       full      SQLite competitive envelope, config `full`, built `--through 5`
#       adaptive  SQLite competitive envelope, config `adaptive`: built minimal
#                 (C0) and LAZILY MATERIALIZED per depth when the schedule reveals
#                 the demand; every `ensure` (re-extraction + DDL/DML) is timed and
#                 charged, and the storage growth it causes is measured
#       hist      the UNMODIFIED Phase-18 baseline control, built `--through 5`
#   * Stage A: each lane's store is built ONCE per document; build wall + persistent
#     bytes recorded.
#   * Stage B/C: the schedule is served as ONE warm session per lane per depth per
#     rep (VOLE is depth-independent: one session serves every depth; SQLite runs
#     one session per depth). Before the timed reps each lane gets one untimed
#     warm-up session per depth; the `adaptive` lane is materialized before that.
#     Reps are interleaved (odd rep VOLE first, even rep SQLite first).
#   * Stage D: the per-rep paired VOLE/SQLite session ratio per depth is aggregated
#     with the ADR-0054 estimator (cluster bootstrap over the 12 documents, fixed
#     seed, +/-10% tie band, median and geometric mean, MDE). Declines are excluded
#     from both numerator and denominator identically (cost per EQUIVALENT
#     successful observation = session cost / |answered by BOTH lanes|).
#
# ## Lane
#
#   Never the host: the digest-pinned, hard-capped `doc-baseline` service
#   (mem_limit == memswap_limit == 6g, pids_limit 4096, cpus 8):
#
#     docker compose run --rm --no-TTY doc-baseline bash tools/phase22-4-lifetime-court.sh
#
#   If BIN and BIN_SKIP_BUILD are set the cargo build is skipped (measure a
#   pre-built binary). Otherwise the release binary is built with all features.
set -uo pipefail

cd /work
export LC_ALL=C
# Never leave root-owned bytecode caches in the tree for the host to clean up.
export PYTHONDONTWRITEBYTECODE=1

SHA=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
STAMP=$(date -u +%Y-%m-%d)
CAMPAIGN=evidence/campaigns/${STAMP}-phase22-4-lifetime-${SHA}${TAG:+-$TAG}
RAW=$CAMPAIGN/raw
WORK=${WORK:-evidence/scratch/phase22-4-lifetime}
rm -rf "$RAW"
mkdir -p "$RAW" "$RAW/sql" "$RAW/sched" "$WORK"

MANIFEST=${MANIFEST:-real100-v1/manifest.tsv}
CORPUS=${CORPUS:-real100-v1/documents}
COMP=tools/fixtures/phase22-competitors.py
CTL=tools/fixtures/phase18-contract-packed.py
SCHED=tools/fixtures/phase22-4-schedule.py
AGG=tools/fixtures/phase22-4-lifetime.py
OP_TIMEOUT=${OP_TIMEOUT:-240}
REPS=${REPS:-25}
BOOT=${BOOT:-20000}
SEED=${SEED:-220400}
TIE=${TIE:-0.10}
SCHED_SEED=${SCHED_SEED:-220400}
SCHED_LEN=${SCHED_LEN:-24}
DEPTHS=${DEPTHS:-0 1 2 3 4 5}
SQLITE_LANES=${SQLITE_LANES:-"full adaptive hist"}
DEFAULT_IDS="nist-pdf-0002 nist-pdf-0004 nist-pdf-0016 nist-pdf-0017 nist-docx-0005 nist-docx-0008 nist-docx-0009 nist-docx-0014 nist-epub-0003 nist-epub-0006 nist-epub-0008 nist-epub-0009"
IDS=${IDS:-$DEFAULT_IDS}
LASTDEP=${DEPTHS##* }

PROFILE=${PROFILE:-release}
case "$PROFILE" in
    release) BUILD_ARGS="--release --locked --all-features"; BIN=${BIN:-target/release/vole-document} ;;
    *)       BUILD_ARGS="--locked --all-features";           BIN=${BIN:-${VOLE_BIN:-target/debug/vole-document}} ;;
esac

if [ -x "$BIN" ] && [ -n "${BIN_SKIP_BUILD:-}" ]; then
    echo "-- using prebuilt $BIN (BIN_SKIP_BUILD set)" >&2
else
    echo "== phase22.4 unknown-query lifetime court (REPS=$REPS, sched_seed=$SCHED_SEED, len=$SCHED_LEN) ==" >&2
    echo "-- building ($PROFILE) binary" >&2
    # shellcheck disable=SC2086
    if ! cargo build $BUILD_ARGS >&2; then
        echo "phase22-4: build FAILED ($BUILD_ARGS); refusing to measure" >&2
        exit 1
    fi
fi
[ -x "$BIN" ] || { echo "phase22-4: $BIN missing; refusing to measure" >&2; exit 1; }

PREFLIGHT=""
for cand in real100-v1/documents/nist/docx/*.docx real100-v1/documents/nasa/epub/*.epub; do
    [ -f "$cand" ] && { PREFLIGHT="$cand"; break; }
done
if [ -n "$PREFLIGHT" ]; then
    expect=$(case "$PREFLIGHT" in *.docx) echo docx ;; *) echo epub ;; esac)
    if ! "$BIN" capabilities "$PREFLIGHT" 2>/dev/null | grep -q "\"adapter\":\"$expect\""; then
        echo "phase22-4: preflight failed — $BIN lacks $expect" >&2
        exit 1
    fi
fi

now_us() { echo $(( ${EPOCHREALTIME/./} )); }
rss_kb() { awk -F': ' '/Maximum resident set size/{print $2}' "$1"; }
fbytes() { find "$@" -type f -printf '%s\n' 2>/dev/null | awk '{s+=$1} END{print s+0}'; }
ffiles() { find "$1" -type f 2>/dev/null | wc -l | tr -d ' '; }
fdirs()  { find "$1" -type d 2>/dev/null | wc -l | tr -d ' '; }

# --- subset selection + revision-family head map (identical to Phase 18/19/22.2) ---
python3 - "$MANIFEST" "$CORPUS" $IDS >"$RAW/subset.tsv" <<'PY'
import sys
manifest, corpus = sys.argv[1], sys.argv[2]
ids = sys.argv[3:]
EXT = {"pdf": "pdf", "docx": "docx", "epub": "epub"}
rows = []
with open(manifest) as f:
    hdr = f.readline().rstrip("\n").split("\t")
    for line in f:
        if not line.strip():
            continue
        r = dict(zip(hdr, line.rstrip("\n").split("\t")))
        rows.append(r)
by_id = {r["id"]: r for r in rows}
heads = {}
for r in rows:
    fam = r["revision_family_id"]
    if not fam:
        continue
    cur = heads.get(fam)
    key = (int(r["byte_len"]),)
    if cur is None or key > cur[0]:
        heads[fam] = (key, r["id"])
for i in ids:
    r = by_id.get(i)
    if not r:
        continue
    fmt = r["format"]
    path = "%s/%s/%s/%s.%s" % (corpus, r["agency"], fmt, i, EXT[fmt])
    fam = r["revision_family_id"]
    is_head = "1" if (not fam or heads.get(fam, (None, i))[1] == i) else "0"
    print("|".join([i, r["agency"], fmt, r["size_class"], r["byte_len"], r["sha256"],
                     path, r["revision_family_id"] or "", is_head]))
PY
echo "-- subset ($(wc -l <"$RAW/subset.tsv" | tr -d ' ') docs)" >&2
cat "$RAW/subset.tsv" >&2

# --- corpus verification (read-only) ---------------------------------------
echo "-- verifying the subset (SHA-256 + length)" >&2
verify_rc=0
while IFS='|' read -r id _a _f _s _bl sha path _fam _head; do
    [ -n "$id" ] || continue
    if [ ! -f "$path" ]; then echo "   missing $path" >&2; verify_rc=1; continue; fi
    got_sha=$(sha256sum "$path" | cut -d' ' -f1)
    got_len=$(stat -c %s "$path")
    if [ "$got_sha" != "$sha" ] || [ "$got_len" != "$_bl" ]; then
        echo "   verify FAIL $id" >&2; verify_rc=1
    fi
done <"$RAW/subset.tsv"
if [ "$verify_rc" -ne 0 ]; then
    echo "phase22-4: corpus verification FAILED; refusing to measure" >&2
    exit 1
fi

# --- contract envelope SQL, generated once (frozen control sql_for) ----------
python3 "$COMP" sqlgen --out "$RAW/sql" --depths "$DEPTHS" >"$RAW/sqlgen.json"

# --- hidden schedules, one per document (frozen by SCHED_SEED) ---------------
# (generated here, once, before any lane runs — the schedule is never tuned.)
echo "-- generating pre-registered hidden schedules (seed=$SCHED_SEED len=$SCHED_LEN)" >&2

# --- raw tables -------------------------------------------------------------
printf 'id\tfmt\tlane\tdepth\trep\trc\tus\trss_kb\tn_req\n' >"$RAW/warm_samples.tsv"
printf 'id\tfmt\tlane\tdepth\trc\tus\tbytes\tfiles\n' >"$RAW/build_bytes.tsv"
printf 'id\tfmt\tlane\tdepth\trc\tus\tbytes_after\tmaterialized\n' >"$RAW/adapt.tsv"
printf 'id\tfmt\tlane\tdepth\tbytes\tfiles\n' >"$RAW/store_shape.tsv"
printf 'id\tfmt\tlane\tok\trc\tus\tsha\tlen\tcmp_src\tcmp_vole\n' >"$RAW/exact.tsv"
printf 'id\trep\torder\n' >"$RAW/order.tsv"
printf 'id\tfmt\tdepth\tlane\tobs\ti\tv_ans\ts_ans\tv_decl\ts_decl\tanswered\n' >"$RAW/answered.tsv"
printf 'id\tfmt\tdepth\tlane\tv_envelope_sha\ts_envelope_sha\tequiv\tmismatch_detail\n' >"$RAW/equiv.tsv"
printf 'id\trep\tk\tcum_us\n' >"$RAW/cumulative_vole.csv"

# --- main loop --------------------------------------------------------------
while IFS='|' read -r id agency fmt sclass blen sha path fam is_head; do
    [ -n "$id" ] || continue
    d="$WORK/$id"; rm -rf "$d"; mkdir -p "$d"
    echo "== $id ($fmt, $sclass, $blen B, family=${fam:-none}, head=$is_head) ==" >&2

    # ---- hidden schedule (pre-registered, seeded per document) ----
    python3 "$SCHED" gen --seed "$SCHED_SEED" --id "$id" --format "$fmt" \
        --length "$SCHED_LEN" --out "$RAW/sched" --sqldir "$RAW/sql" --depths "$DEPTHS" \
        >"$d/sched.json" 2>"$d/sched.err" || { echo "   schedule gen FAILED" >&2; continue; }
    nreq=$(wc -l <"$RAW/sched/$id.vole.reqs" | tr -d ' ')
    echo "   schedule: $nreq requests (see raw/sched/$id.schedule.json)" >&2

    # ================= Stage A — ingest (one build per lane) =================
    field=""
    rm -rf "$d/vstore"
    t0=$(now_us)
    timeout "$OP_TIMEOUT" "$BIN" field-build "$path" --store "$d/vstore" \
        --profile runtime --packed >"$d/vole.build.json" 2>"$d/vole.build.err"; rc=$?
    t1=$(now_us)
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$id" "$fmt" "vole" "all" "$rc" "$(( t1 - t0 ))" \
        "$(fbytes "$d/vstore")" "$(ffiles "$d/vstore")" >>"$RAW/build_bytes.tsv"
    [ "$rc" -eq 0 ] && field=$(jq -r '.ingest.field // empty' "$d/vole.build.json" 2>/dev/null)
    echo "   vole field-build rc=$rc field=${field:-none}" >&2
    printf '%s\t%s\t%s\t%s\t%s\t%s\n' "$id" "$fmt" "vole" "all" \
        "$(fbytes "$d/vstore")" "$(ffiles "$d/vstore")" >>"$RAW/store_shape.tsv"

    # SQLite `full` at C5
    rm -f "$d/full.db" "$d/full.db-wal" "$d/full.db-shm"
    t0=$(now_us)
    timeout "$OP_TIMEOUT" python3 "$COMP" build --config full --format "$fmt" --source "$path" \
        --db "$d/full.db" --through "$LASTDEP" --durability normal \
        --family "$fam" --member "$id" --is-head "$is_head" --metrics "$d/full.m.json" \
        >"$d/full.build.json" 2>"$d/full.build.err"; rc=$?
    t1=$(now_us)
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$id" "$fmt" "full" "$LASTDEP" "$rc" "$(( t1 - t0 ))" \
        "$(find "$d" -maxdepth 1 -name 'full.db*' -type f -printf '%s\n' | awk '{s+=$1} END{print s+0}')" \
        "$(find "$d" -maxdepth 1 -name 'full.db*' -type f | wc -l | tr -d ' ')" >>"$RAW/build_bytes.tsv"
    printf '%s\t%s\t%s\t%s\t%s\t%s\n' "$id" "$fmt" "full" "$LASTDEP" \
        "$(find "$d" -maxdepth 1 -name 'full.db*' -type f -printf '%s\n' | awk '{s+=$1} END{print s+0}')" \
        "$(find "$d" -maxdepth 1 -name 'full.db*' -type f | wc -l | tr -d ' ')" \
        >>"$RAW/store_shape.tsv"
    echo "   sqlite full build rc=$rc (through C$LASTDEP)" >&2

    # SQLite `adaptive` minimal (C0); materialized lazily below
    rm -f "$d/adaptive.db" "$d/adaptive.db-wal" "$d/adaptive.db-shm"
    t0=$(now_us)
    timeout "$OP_TIMEOUT" python3 "$COMP" build --config adaptive --format "$fmt" --source "$path" \
        --db "$d/adaptive.db" --through 0 --durability normal \
        --family "$fam" --member "$id" --is-head "$is_head" --metrics "$d/adaptive.m.json" \
        >"$d/adaptive.build.json" 2>"$d/adaptive.build.err"; rc=$?
    t1=$(now_us)
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$id" "$fmt" "adaptive" "0" "$rc" "$(( t1 - t0 ))" \
        "$(find "$d" -maxdepth 1 -name 'adaptive.db*' -type f -printf '%s\n' | awk '{s+=$1} END{print s+0}')" \
        "$(find "$d" -maxdepth 1 -name 'adaptive.db*' -type f | wc -l | tr -d ' ')" >>"$RAW/build_bytes.tsv"
    echo "   sqlite adaptive minimal build rc=$rc" >&2

    # hist control at C5
    rm -f "$d/hist.db" "$d/hist.db-wal" "$d/hist.db-shm"
    t0=$(now_us)
    timeout "$OP_TIMEOUT" python3 "$CTL" build --format "$fmt" --source "$path" \
        --db "$d/hist.db" --through "$LASTDEP" --family "$fam" --member "$id" \
        --is-head "$is_head" --metrics "$d/hist.m.json" \
        >"$d/hist.build.json" 2>"$d/hist.build.err"; rc=$?
    t1=$(now_us)
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$id" "$fmt" "hist" "$LASTDEP" "$rc" "$(( t1 - t0 ))" \
        "$(find "$d" -maxdepth 1 -name 'hist.db*' -type f -printf '%s\n' | awk '{s+=$1} END{print s+0}')" \
        "$(find "$d" -maxdepth 1 -name 'hist.db*' -type f | wc -l | tr -d ' ')" >>"$RAW/build_bytes.tsv"
    printf '%s\t%s\t%s\t%s\t%s\t%s\n' "$id" "$fmt" "hist" "$LASTDEP" \
        "$(find "$d" -maxdepth 1 -name 'hist.db*' -type f -printf '%s\n' | awk '{s+=$1} END{print s+0}')" \
        "$(find "$d" -maxdepth 1 -name 'hist.db*' -type f | wc -l | tr -d ' ')" \
        >>"$RAW/store_shape.tsv"
    echo "   sqlite hist build rc=$rc (through C$LASTDEP)" >&2

    # ============ Stage C-adapt — lazy materialization, ALL charged ============
    # The schedule reveals the demand for each contract depth; the adaptive lane
    # materializes it on first demand (re-extraction + DDL/DML + index), timed and
    # charged in full, and its storage growth is measured.
    for dep in $DEPTHS; do
        [ "$dep" = "0" ] && continue   # C0 == the minimal store already built
        t0=$(now_us)
        timeout "$OP_TIMEOUT" python3 "$COMP" ensure --config adaptive \
            --db "$d/adaptive.db" --format "$fmt" --source "$path" --depth "$dep" \
            --family "$fam" --member "$id" --is-head "$is_head" \
            --metrics "$d/adaptive.ensure.C$dep.json" >"$d/adaptive.ensure.C$dep.out" \
            2>"$d/adaptive.ensure.C$dep.err"; rc=$?
        t1=$(now_us)
        matd=$(jq -r '(.materialized // []) | join(",")' "$d/adaptive.ensure.C$dep.json" 2>/dev/null)
        printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$id" "$fmt" "adaptive" "$dep" "$rc" "$(( t1 - t0 ))" \
            "$(find "$d" -maxdepth 1 -name 'adaptive.db*' -type f -printf '%s\n' | awk '{s+=$1} END{print s+0}')" \
            "${matd:-none}" >>"$RAW/adapt.tsv"
        printf '%s\t%s\t%s\t%s\t%s\t%s\n' "$id" "$fmt" "adaptive" "C$dep" \
            "$(find "$d" -maxdepth 1 -name 'adaptive.db*' -type f -printf '%s\n' | awk '{s+=$1} END{print s+0}')" \
            "$(find "$d" -maxdepth 1 -name 'adaptive.db*' -type f | wc -l | tr -d ' ')" \
            >>"$RAW/store_shape.tsv"
    done
    echo "   adaptive materialized (see raw/adapt.tsv)" >&2

    # ---- untimed warm-up: one session per lane per depth.
    # Peak RSS is measured HERE (under /usr/bin/time -v) so the timed reps below
    # carry NO `time` wrapper overhead in the measured wall.
    declare -A RSS=()
    if [ -n "$field" ]; then
        timeout "$OP_TIMEOUT" /usr/bin/time -v "$BIN" observe-batch --store "$d/vstore" --packed \
            --field "$field" --requests "$RAW/sched/$id.vole.reqs" \
            >/dev/null 2>"$d/warm.vole.time" || true
        rv=$(rss_kb "$d/warm.vole.time" | tr -d ' ')
        for dep in $DEPTHS; do RSS["vole:$dep"]="${rv:-0}"; done
    fi
    for lane in $SQLITE_LANES; do
        case "$lane" in
            full)     db="$d/full.db" ;;
            adaptive) db="$d/adaptive.db" ;;
            hist)     db="$d/hist.db" ;;
        esac
        for dep in $DEPTHS; do
            timeout "$OP_TIMEOUT" /usr/bin/time -v sqlite3 -batch "$db" \
                "$(cat "$RAW/sched/$id.sched.C$dep.sql")" \
                >/dev/null 2>"$d/warm.$lane.C$dep.time" || true
            RSS["$lane:$dep"]="$(rss_kb "$d/warm.$lane.C$dep.time" | tr -d ' ')"
        done
    done

    # ---- timed warm reps (interleaved) ----
    for rep in $(seq 1 "$REPS"); do
        if [ $(( rep % 2 )) -eq 1 ]; then order="vole sqlite"; else order="sqlite vole"; fi
        printf '%s\t%s\t%s\n' "$id" "$rep" "$order" >>"$RAW/order.tsv"
        [ $(( rep % 5 )) -eq 1 ] && echo "   rep $rep/$REPS (order: $order)" >&2

        for grp in $order; do
            if [ "$grp" = vole ]; then
                if [ -z "$field" ]; then
                    for dep in $DEPTHS; do
                        printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$id" "$fmt" "vole" "$dep" "$rep" 3 0 0 "$nreq" >>"$RAW/warm_samples.tsv"
                    done
                    continue
                fi
                out="$d/vole.warm.$rep.jsonl"
                t0=$(now_us)
                timeout "$OP_TIMEOUT" "$BIN" observe-batch --store "$d/vstore" --packed \
                    --field "$field" --requests "$RAW/sched/$id.vole.reqs" \
                    >"$out" 2>"$d/vole.warm.$rep.err"; rc=$?
                t1=$(now_us)
                # depth-independent: same session serves every depth
                for dep in $DEPTHS; do
                    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$id" "$fmt" "vole" "$dep" "$rep" "$rc" \
                        "$(( t1 - t0 ))" "${RSS[vole:$dep]:-0}" "$nreq" >>"$RAW/warm_samples.tsv"
                done
                # descriptive cumulative curve from the per-request stats (VOLE-only;
                # the sqlite3 CLI exposes no sub-ms per-statement wall)
                if [ "$rc" -eq 0 ]; then
                    python3 - "$out" "$id" "$rep" >>"$RAW/cumulative_vole.csv" <<'PY'
import json, sys
path, idv, rep = sys.argv[1], sys.argv[2], sys.argv[3]
cum = 0
with open(path) as f:
    for k, line in enumerate(f):
        line = line.strip()
        if not line:
            continue
        try:
            o = json.loads(line)
        except json.JSONDecodeError:
            continue
        st = o.get("stats") or {}
        cum += int(st.get("wall_micros", 0))
        print("%s\t%s\t%d\t%d" % (idv, rep, k, cum))
PY
                fi
            else
                for lane in $SQLITE_LANES; do
                    case "$lane" in
                        full)     db="$d/full.db" ;;
                        adaptive) db="$d/adaptive.db" ;;
                        hist)     db="$d/hist.db" ;;
                    esac
                    for dep in $DEPTHS; do
                        t0=$(now_us)
                        timeout "$OP_TIMEOUT" sqlite3 -batch "$db" \
                            "$(cat "$RAW/sched/$id.sched.C$dep.sql")" \
                            >/dev/null 2>"$d/$lane.C$dep.warm.$rep.err"; rc=$?
                        t1=$(now_us)
                        printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$id" "$fmt" "$lane" "$dep" "$rep" "$rc" \
                            "$(( t1 - t0 ))" "${RSS[$lane:$dep]:-0}" "$nreq" >>"$RAW/warm_samples.tsv"
                    done
                done
            fi
        done
    done
    # ---- untimed equivalence pass + answered sets (retain result, not bodies) ----
    for dep in $DEPTHS; do
        if [ -n "$field" ]; then
            timeout "$OP_TIMEOUT" "$BIN" observe-batch --store "$d/vstore" --packed \
                --field "$field" --requests "$RAW/sched/$id.vole.reqs" \
                >"$d/equiv.vole.C$dep.jsonl" 2>/dev/null || true
        else
            : >"$d/equiv.vole.C$dep.jsonl"
        fi
        for lane in $SQLITE_LANES; do
            case "$lane" in
                full)     db="$d/full.db" ;;
                adaptive) db="$d/adaptive.db" ;;
                hist)     db="$d/hist.db" ;;
            esac
            timeout "$OP_TIMEOUT" sqlite3 -batch "$db" "$(cat "$RAW/sched/$id.sched.C$dep.sql")" \
                >"$d/equiv.$lane.C$dep.jsonl" 2>/dev/null || true
        done
    done
    python3 - "$id" "$fmt" "$d" "$RAW" "$DEPTHS" "$SQLITE_LANES" <<'PY'
import json, os, sys, importlib.util
idv, fmt, d, raw, depths_s, lanes_s = sys.argv[1:7]
depths = depths_s.split()
lanes = lanes_s.split()
here = "/work/tools/fixtures"  # the court cd's to /work; __file__ is undefined on stdin

def load(name, fname):
    spec = importlib.util.spec_from_file_location(name, os.path.join(here, fname))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod

P18 = load("p18_eq", "phase18-contract-packed.py")
sched = json.load(open(os.path.join(raw, "sched", idv + ".schedule.json")))
seq = sched["schedule"]

def rd(path):
    out = []
    try:
        with open(path) as f:
            for line in f:
                line = line.strip()
                if line:
                    out.append(line)
    except OSError:
        return []
    return out

af = open(os.path.join(raw, "answered.tsv"), "a")
ef = open(os.path.join(raw, "equiv.tsv"), "a")
for dstr in depths:
    dep = int(dstr)
    vlines = rd(os.path.join(d, "equiv.vole.C%d.jsonl" % dep))
    for lane in lanes:
        slines = rd(os.path.join(d, "equiv.%s.C%d.jsonl" % (lane, dep)))
        for i, obs in enumerate(seq):
            vraw = None
            if i < len(vlines):
                try:
                    vraw = json.loads(vlines[i])
                except ValueError:
                    vraw = None
            sraw = None
            if i < len(slines):
                try:
                    sraw = json.loads(slines[i])
                except ValueError:
                    sraw = None
            v_decl = not isinstance(vraw, dict) or ("stats" not in vraw)
            s_decl = not isinstance(sraw, dict) or bool(sraw.get("declined"))
            if v_decl:
                v = {"obs": obs, "declined": True, "lane": "vole",
                     "reason": "typed decline"}
            else:
                v = P18._normalize_vole_answer(vraw, fmt, obs, dep)
            s = sraw if isinstance(sraw, dict) else None
            result, detail = P18._equiv(dep, fmt, obs, v, s)
            answered = 0 if (v_decl or s_decl) else 1
            af.write("%s\t%s\t%d\t%s\t%s\t%d\t%d\t%d\t%d\t%d\t%d\n" % (
                idv, fmt, dep, lane, obs, i, 0 if v_decl else 1, 0 if s_decl else 1,
                1 if v_decl else 0, 1 if s_decl else 0, answered))
            if lane == "full":
                vsha = P18.sha256_hex(json.dumps(v, sort_keys=True).encode())
                ssha = P18.sha256_hex(json.dumps(s, sort_keys=True).encode())
                ef.write("%s\t%s\t%d\t%s\t%s\t%s\t%s\t%s\n" % (
                    idv, fmt, dep, lane, vsha, ssha, result,
                    "" if result != "mismatch" else detail.replace("\t", " ")))
af.close(); ef.close()
PY
    # drop the temporary equivalence bodies
    rm -f "$d"/equiv.*.jsonl

    # ---- exact original closure (both lanes) ----
    v_sha=""; v_len=0; v_ok=0; v_rc=3; v_us=0; v_cmp="n/a"
    if [ -n "$field" ]; then
        t0=$(now_us)
        timeout "$OP_TIMEOUT" "$BIN" materialize --store "$d/vstore" --field "$field" \
            --exact --output "$d/v.exact.bin" --packed >/dev/null 2>"$d/v.exact.err"; v_rc=$?
        t1=$(now_us); v_us=$(( t1 - t0 ))
        v_sha=$(sha256sum "$d/v.exact.bin" 2>/dev/null | cut -d' ' -f1)
        v_len=$(stat -c %s "$d/v.exact.bin" 2>/dev/null || echo 0)
        [ "$v_sha" = "$sha" ] && [ "$v_len" = "$blen" ] && v_ok=1
        if cmp -s "$d/v.exact.bin" "$path"; then v_cmp="eq"; else v_cmp="ne"; fi
    fi
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$id" "$fmt" "vole" "$v_ok" "$v_rc" "$v_us" \
        "$v_sha" "$v_len" "$v_cmp" "n/a" >>"$RAW/exact.tsv"
    for lane in $SQLITE_LANES; do
        case "$lane" in
            full)     db="$d/full.db" ;;
            adaptive) db="$d/adaptive.db" ;;
            hist)     db="$d/hist.db" ;;
        esac
        t0=$(now_us)
        timeout "$OP_TIMEOUT" python3 "$COMP" materialize --db "$db" --out "$d/$lane.exact.bin" \
            >/dev/null 2>"$d/$lane.exact.err"; rc=$?
        t1=$(now_us)
        s=$(sha256sum "$d/$lane.exact.bin" 2>/dev/null | cut -d' ' -f1)
        l=$(stat -c %s "$d/$lane.exact.bin" 2>/dev/null || echo 0)
        ok=0; [ "$s" = "$sha" ] && [ "$l" = "$blen" ] && ok=1
        cmp_src="ne"; cmp -s "$d/$lane.exact.bin" "$path" && cmp_src="eq"
        cmp_v="n/a"
        if [ -f "$d/v.exact.bin" ]; then cmp_v="ne"; cmp -s "$d/$lane.exact.bin" "$d/v.exact.bin" && cmp_v="eq"; fi
        printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$id" "$fmt" "$lane" "$ok" "$rc" "$(( t1 - t0 ))" \
            "$s" "$l" "$cmp_src" "$cmp_v" >>"$RAW/exact.tsv"
    done

    rm -rf "$d"
done <"$RAW/subset.tsv"

# --- provenance -------------------------------------------------------------
RUSTC_V=$(rustc --version 2>/dev/null | sed 's/"/\\"/g')
CARGO_V=$(cargo --version 2>/dev/null | sed 's/"/\\"/g')
ARCH=$(uname -m)
COMMIT=$(git rev-parse HEAD 2>/dev/null || echo unknown)
DIRTY=$(git --no-optional-locks status --porcelain 2>/dev/null | tr '\n' ';' | sed 's/"/\\"/g')
LOCK_SHA=$(sha256sum Cargo.lock 2>/dev/null | cut -d' ' -f1)
MANIFEST_SHA=$(sha256sum "$MANIFEST" | cut -d' ' -f1)
BIN_SHA=$(sha256sum "$BIN" 2>/dev/null | cut -d' ' -f1)
SQLITE_V=$(sqlite3 --version 2>/dev/null | cut -d' ' -f1)
PY_V=$(python3 --version 2>&1)
JQ_V=$(jq --version 2>/dev/null)
BASE_STABLE=$(sed -n 's/^ARG BASE_STABLE=//p' Dockerfile | head -1)
DOC_IMAGE="vole-document/doc-baseline:1.99.0"
SCHED_SHA=$(cat "$RAW"/sched/*.schedule.json 2>/dev/null | sha256sum | cut -d' ' -f1)

cat >"$RAW/environment.json" <<EOF
{
  "campaign": "$CAMPAIGN",
  "phase": "22.4 — unknown-query lifetime frontier per equivalent successful observation (measurement court)",
  "utc": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "git_commit": "$COMMIT",
  "git_dirty": "$DIRTY",
  "arch": "$ARCH",
  "service": "doc-baseline",
  "service_caps": "mem_limit == memswap_limit == 6g, pids_limit 4096, cpus 8",
  "service_image": "$DOC_IMAGE",
  "base_image": "$BASE_STABLE",
  "rustc": "$RUSTC_V",
  "cargo": "$CARGO_V",
  "sqlite3": "$SQLITE_V",
  "python": "$PY_V",
  "jq": "$JQ_V",
  "cargo_lock_sha256": "$LOCK_SHA",
  "manifest": "$MANIFEST",
  "manifest_sha256": "$MANIFEST_SHA",
  "bin": "$BIN",
  "bin_sha256": "$BIN_SHA",
  "profile": "$PROFILE",
  "subset": "$DEFAULT_IDS",
  "depths": "$DEPTHS",
  "reps": $REPS,
  "schedule_seed": $SCHED_SEED,
  "schedule_length": $SCHED_LEN,
  "schedule_sha256_concat": "$SCHED_SHA",
  "bootstrap_resamples": $BOOT,
  "bootstrap_seed": $SEED,
  "tie_band": $TIE,
  "op_timeout_s": $OP_TIMEOUT,
  "sqlite_lanes": "$SQLITE_LANES",
  "predeclared_budget": "contract ceiling C5 (full/hist built --through 5; adaptive built minimal and lazily materialized up to C5; VOLE field-build --profile runtime --packed)",
  "accounting": "persistent bytes = sum of regular-file sizes (find -printf %s); du -sb never used",
  "equivalence": "untimed pass per (doc, depth, lane): VOLE observe-batch JSONL vs the SQLite session JSONL, compared with the frozen Phase-18 _equiv; answer bodies are not retained (result + divergence detail are, in raw/equiv.tsv), only timing samples are retained raw",
  "adaptation": "adaptive ensure(depth) timed and charged in full (raw/adapt.tsv); storage growth measured after each ensure",
  "env_affecting_semantics": {"LC_ALL": "C", "PYTHONDONTWRITEBYTECODE": "1", "VOLE_BIN": "ignored under PROFILE=release"}
}
EOF
cp "$RAW/environment.json" "$CAMPAIGN/environment.json"

cat >"$CAMPAIGN/commands.txt" <<'EOF'
# Phase 22.4 — unknown-query lifetime court. Never on the host.
docker compose run --rm --no-TTY doc-baseline bash tools/phase22-4-lifetime-court.sh

# bounded / explicit population:
docker compose run --rm --no-TTY doc-baseline sh -c 'REPS=10 IDS="nist-pdf-0017 nist-docx-0005" bash tools/phase22-4-lifetime-court.sh'

# per-document CLI the court drives (inside the container, /work = repo root):
#   tools/fixtures/phase22-4-schedule.py gen --seed S --id ID --format FMT --length L \
#       --out RAW/sched --sqldir RAW/sql --depths "0 1 2 3 4 5"
#   BIN field-build <source> --store <dir> --profile runtime --packed
#   python3 tools/fixtures/phase22-competitors.py build --config {full|adaptive} ...
#   python3 tools/fixtures/phase22-competitors.py ensure --config adaptive --depth D ...
#   python3 tools/fixtures/phase18-contract-packed.py build ...   (hist control)
#   /usr/bin/time -v BIN observe-batch --store <dir> --packed --field <hex> --requests <reqs>
#   /usr/bin/time -v sqlite3 -batch <db> "<sched.CD.sql>"
# aggregate:
#   python3 tools/fixtures/phase22-4-lifetime.py RAW CAMPAIGN --reps R --boot B --seed S --tie T
EOF

# --- aggregate + seal -------------------------------------------------------
echo "-- aggregating" >&2
python3 "$AGG" "$RAW" "$CAMPAIGN" --reps "$REPS" --boot "$BOOT" --seed "$SEED" --tie "$TIE" \
    | tee "$RAW/summary.txt"

VERDICT=$(grep '^verdict=' "$CAMPAIGN/counts.txt" | head -1 | cut -d= -f2-)
cat >"$CAMPAIGN/receipt.json" <<EOF
{
  "campaign": "$CAMPAIGN",
  "phase": "22.4 — unknown-query lifetime frontier (measurement court)",
  "utc": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "measured_commit": "$COMMIT",
  "tree_state": "$DIRTY",
  "profile": "$PROFILE",
  "bin": "$BIN",
  "bin_sha256": "$BIN_SHA",
  "base_image": "$BASE_STABLE",
  "service_image": "$DOC_IMAGE",
  "service": "doc-baseline (mem_limit == memswap_limit == 6g, pids_limit 4096, cpus 8)",
  "rustc": "$RUSTC_V",
  "cargo": "$CARGO_V",
  "sqlite3": "$SQLITE_V",
  "cargo_lock_sha256": "$LOCK_SHA",
  "manifest_sha256": "$MANIFEST_SHA",
  "op_timeout_s": $OP_TIMEOUT,
  "reps": $REPS,
  "bootstrap_resamples": $BOOT,
  "bootstrap_seed": $SEED,
  "tie_band": $TIE,
  "depths": "$DEPTHS",
  "court": "tools/phase22-4-lifetime-court.sh",
  "schedule_generator": "tools/fixtures/phase22-4-schedule.py",
  "aggregator": "tools/fixtures/phase22-4-lifetime.py (reuses the phase-19.1/ADR-0054 statistics primitives)",
  "schedule_seed": $SCHED_SEED,
  "schedule_length": $SCHED_LEN,
  "schedule_sha256_concat": "$SCHED_SHA",
  "sqlite_primary": "tools/fixtures/phase22-competitors.py config=full (the Phase-22.1 tuned envelope)",
  "sqlite_adaptive": "tools/fixtures/phase22-competitors.py config=adaptive (built minimal; ensure() charged)",
  "hist_control": "tools/fixtures/phase18-contract-packed.py (UNMODIFIED historical control), --through 5",
  "verdict": "$VERDICT",
  "claim": "measurement-only: per-region paired VOLE/SQLite cumulative-session ratios with an interval, MDE and W/T/L, plus build/bytes/RSS frontier axes; every adaptation charged",
  "does_not_prove": "no production code changed and nothing ships; regions where the CI still includes 1.0 are reported as unresolved, never as parity",
  "rc_codes": "0 ok; 3 decline; 6 unsupported-feature; 124 timeout; 137 SIGKILL/OOM"
}
EOF

chown -R 1000:1000 "$CAMPAIGN" "$WORK" 2>/dev/null || true

echo "phase22.4 lifetime court: done — $CAMPAIGN (verdict=$VERDICT)"
