#!/bin/sh
# Phase 21.17.1 — JSON5 / JSONC (structured-extra Wave 2) surface + exact closure.
#
# Pre-registered (Phase-21 subphase 21.17.1). Hypotheses:
#
#   H1 (byte-exactness) — for every fixture, `materialize(field) == source`
#       (length + SHA-256 + cmp) after the source file AND the standalone
#       descriptor are deleted, in a fresh process. The court FAILS unless this is
#       100% on every fixture.
#   H2 (surface + preserved representation) — the representation-preserving model
#       is exposed: comments (exact spans, never dropped), unquoted keys,
#       single-quoted strings, trailing commas, hex/leading-dot/`Infinity`/`NaN`
#       numbers, string continuations, the extended whitespace set, member order,
#       duplicate keys, numeric/escape spelling, and the recorded dialect (`jsonc`
#       vs `json5`). Common metadata/text/search-match and native
#       json5-pointer/json5-node/json5-find/json5-comments answer.
#   H3 (honest declines / boundaries) — an out-of-range pointer declines typed with
#       exit code 6, never a silent empty answer. The controls pin the detection
#       boundaries: `strict.json` stays `Json` (a native JSON5 selector on it
#       declines typed); `malformed.json5` and `prose.txt` stay `Opaque` and a
#       common observation declines typed.
#
# Runs in the pinned `dev` service (Rust toolchain + git + coreutils + sed/grep;
# deliberately NO python3 and NO jq, so the court depends only on the shipped
# binary and POSIX shell):
#   docker compose run --rm --no-TTY dev sh tools/phase21-17-1-json5-court.sh

set -eu
cd /work
LC_ALL=C
export LC_ALL
export PYTHONDONTWRITEBYTECODE=1

BIN=target/debug/vole-document
SHA="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
STAMP="$(date -u +%Y-%m-%d)"
CAMPAIGN="evidence/campaigns/${STAMP}-phase21-17-1-json5-${SHA}"
RAW="$CAMPAIGN/raw"
rm -rf "$CAMPAIGN"
mkdir -p "$RAW"

WORK=evidence/scratch/phase21-17
rm -rf "$WORK"
mkdir -p "$WORK/corpus" "$WORK/ref" "$WORK/store"

echo "=== build (all-features) ==="
cargo build --locked --all-features 2>&1 | tail -2

echo "=== assemble fixtures ==="
# The small fixtures are committed (generated by tools/fixtures/make-json5.py).
for f in basic.json5 jsonc.jsonc numbers.json5 strings.json5 unicode.json5 \
         comments.json5 strict.json malformed.json5 prose.txt; do
    cp "tools/fixtures/json5/$f" "$WORK/corpus/$f"
done

# The large fixture is regenerated here (gitignored) with POSIX printf only, so the
# court needs no python3.
gen_large() {
    out="$1"
    i=0
    printf '[' > "$out"
    while [ "$i" -lt 4000 ]; do
        printf "{ id: %d, name: 'item-%d', value: 0x%X, ratio: .%02d, tags: ['t%d','t%d',], ok: true },\n" \
            "$i" "$i" "$i" "$((i % 100))" "$i" "$((i + 1))" >> "$out"
        i=$((i + 1))
    done
    printf ']\n' >> "$out"
}
gen_large "$WORK/corpus/large.json5"

ALL="basic.json5 jsonc.jsonc numbers.json5 strings.json5 unicode.json5 comments.json5 large.json5 strict.json malformed.json5 prose.txt"
NORMAL="basic.json5 jsonc.jsonc numbers.json5 strings.json5 unicode.json5 comments.json5 large.json5"
JSONCTL="strict.json"
OPAQUE="malformed.json5 prose.txt"

ptr_for() {
    case "$1" in
        basic.json5)    echo "/unquoted" ;;
        jsonc.jsonc)    echo "/compilerOptions/target" ;;
        numbers.json5)  echo "/inf" ;;
        strings.json5)  echo "/hex" ;;
        unicode.json5)  echo "/esc" ;;
        comments.json5) echo "/b" ;;
        large.json5)    echo "/5/name" ;;
        *)              echo "/" ;;
    esac
}
find_for() {
    case "$1" in
        basic.json5)    echo "trail" ;;
        jsonc.jsonc)    echo "target" ;;
        numbers.json5)  echo "inf" ;;
        strings.json5)  echo "uni" ;;
        unicode.json5)  echo "esc" ;;
        comments.json5) echo "not a comment" ;;
        large.json5)    echo "item-5" ;;
        *)              echo "z" ;;
    esac
}
# An out-of-range pointer that must decline typed (rc 6). The large fixture's root
# is an array, so an out-of-range *index* is required (a non-numeric segment would
# be a usage error, rc 2).
decline_for() {
    case "$1" in
        large.json5) echo "/999999" ;;
        *)           echo "/nope/nope" ;;
    esac
}
is_in() {
    for x in $2; do [ "$x" = "$1" ] && return 0; done
    return 1
}
# Extract one JSON string field from a single-line JSON object (greedy, no jq).
json_str() {
    # $1 = json, $2 = key
    printf '%s' "$1" | sed -n "s/.*\"$2\":\"\([^\"]*\)\".*/\1/p"
}

TSV="$RAW/results.tsv"
: > "$TSV"
printf 'fixture\tformat\tsrc_len\tsrc_sha\tout_len\tout_sha\tcmp\texact\tdecline_rc\tctl_rc\n' >> "$TSV"

exact_ok=0
exact_fail=0
surface_fail=0
declines_ok=0
json_ctl_ok=0
opaque_ok=0
opaque_n=0
normal_n=0

for f in $ALL; do
    # The reference copy is never deleted; the corpus copy is what is ingested and
    # then removed (so the identity comparison is against retained bytes).
    src="$WORK/ref/$f"
    cp "$WORK/corpus/$f" "$src"
    src_len="$(wc -c < "$src" | tr -d ' ')"
    src_sha="$(sha256sum "$src" | cut -d' ' -f1)"

    build_json="$("$BIN" field-build "$WORK/corpus/$f" --store "$WORK/store" \
        --voldoc "$WORK/$f.voldoc")"
    field="$(json_str "$build_json" field)"
    fmt="$(json_str "$build_json" format)"

    decline_rc=-1
    ctl_rc=-1

    if is_in "$f" "$NORMAL"; then
        normal_n=$((normal_n + 1))
        [ "$fmt" = "json5" ] || { echo "FINDING: $f not detected as json5 (fmt=$fmt)" >&2; surface_fail=$((surface_fail + 1)); }

        # H2: common metadata / text + native pointer (exact bytes) / node / find /
        # comments.
        "$BIN" observe --store "$WORK/store" --field "$field" --metadata --kind metadata \
            > "$RAW/$f.metadata.json" 2>&1 || surface_fail=$((surface_fail + 1))
        "$BIN" observe --store "$WORK/store" --field "$field" --doc-text --kind text \
            > "$RAW/$f.text.json" 2>&1 || surface_fail=$((surface_fail + 1))
        "$BIN" observe --store "$WORK/store" --field "$field" --json5-pointer "$(ptr_for "$f")" --kind exact \
            > "$RAW/$f.ptr.bin" 2>&1 || surface_fail=$((surface_fail + 1))
        "$BIN" observe --store "$WORK/store" --field "$field" --json5-pointer "$(ptr_for "$f")" --kind metadata \
            > "$RAW/$f.ptr.json" 2>&1 || surface_fail=$((surface_fail + 1))
        "$BIN" observe --store "$WORK/store" --field "$field" --json5-node "" --kind structure \
            > "$RAW/$f.node.json" 2>&1 || surface_fail=$((surface_fail + 1))
        "$BIN" observe --store "$WORK/store" --field "$field" --json5-find "$(find_for "$f")" --kind text \
            > "$RAW/$f.find.json" 2>&1 || surface_fail=$((surface_fail + 1))
        "$BIN" observe --store "$WORK/store" --field "$field" --json5-comments --kind metadata \
            > "$RAW/$f.comments.json" 2>&1 || surface_fail=$((surface_fail + 1))

        grep -q '"format":"json5"' "$RAW/$f.metadata.json" || { echo "FINDING: $f metadata missing format" >&2; surface_fail=$((surface_fail + 1)); }

        # Dialect boundary: jsonc.jsonc must be jsonc; the rest json5.
        if [ "$f" = "jsonc.jsonc" ]; then
            grep -q '"dialect":"jsonc"' "$RAW/$f.metadata.json" || { echo "FINDING: jsonc dialect not recorded" >&2; surface_fail=$((surface_fail + 1)); }
        else
            grep -q '"dialect":"json5"' "$RAW/$f.metadata.json" || { echo "FINDING: $f dialect not json5" >&2; surface_fail=$((surface_fail + 1)); }
        fi

        # H3: an out-of-range pointer declines typed (rc 6).
        set +e
        "$BIN" observe --store "$WORK/store" --field "$field" --json5-pointer "$(decline_for "$f")" --kind metadata \
            > /dev/null 2>&1
        decline_rc=$?
        set -e
        [ "$decline_rc" -eq 6 ] && declines_ok=$((declines_ok + 1)) || { echo "FINDING: $f decline rc=$decline_rc (want 6)" >&2; }

    elif [ "$f" = "$JSONCTL" ]; then
        # H3: strict JSON stays `Json`; a native JSON5 selector on it declines (rc 6).
        [ "$fmt" = "json" ] || { echo "FINDING: control $f detected as $fmt (want json)" >&2; surface_fail=$((surface_fail + 1)); }
        set +e
        "$BIN" observe --store "$WORK/store" --field "$field" --json5-pointer "/a" --kind metadata \
            > "$RAW/$f.json5-decline.json" 2>&1
        ctl_rc=$?
        set -e
        [ "$ctl_rc" -eq 6 ] && json_ctl_ok=$((json_ctl_ok + 1)) || { echo "FINDING: strict JSON json5 selector rc=$ctl_rc (want 6)" >&2; }

    elif is_in "$f" "$OPAQUE"; then
        # H3: not detected as JSON5; the common observation declines typed (rc 6).
        [ "$fmt" = "opaque" ] || { echo "FINDING: control $f detected as $fmt (want opaque)" >&2; surface_fail=$((surface_fail + 1)); }
        set +e
        "$BIN" observe --store "$WORK/store" --field "$field" --metadata --kind metadata \
            > "$RAW/$f.metadata.json" 2>&1
        ctl_rc=$?
        set -e
        [ "$ctl_rc" -eq 6 ] && opaque_ok=$((opaque_ok + 1)) || { echo "FINDING: opaque control $f metadata rc=$ctl_rc (want 6)" >&2; }
        opaque_n=$((opaque_n + 1))
    fi

    # H1: delete the source AND the standalone descriptor, then rematerialize
    # exactly in a fresh process and compare (length + SHA-256 + cmp).
    rm -f "$WORK/corpus/$f" "$WORK/$f.voldoc"
    "$BIN" materialize --store "$WORK/store" --field "$field" --exact \
        --output "$WORK/$f.out" > /dev/null
    out_len="$(wc -c < "$WORK/$f.out" | tr -d ' ')"
    out_sha="$(sha256sum "$WORK/$f.out" | cut -d' ' -f1)"
    if cmp -s "$src" "$WORK/$f.out"; then cmp_ok=true; else cmp_ok=false; fi
    if [ "$out_len" = "$src_len" ] && [ "$out_sha" = "$src_sha" ] && [ "$cmp_ok" = true ]; then
        exact=true; exact_ok=$((exact_ok + 1))
    else
        exact=false; exact_fail=$((exact_fail + 1))
        echo "FINDING: not byte-exact after removal: $f" >&2
    fi

    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
        "$f" "$fmt" "$src_len" "$src_sha" "$out_len" "$out_sha" "$cmp_ok" "$exact" \
        "$decline_rc" "$ctl_rc" >> "$TSV"
done

echo "=== exactness after source + descriptor deletion ==="
cat "$TSV"

fixtures_n="$(printf '%s\n' $ALL | wc -w | tr -d ' ')"

# --- MATRIX.md --------------------------------------------------------------
{
    echo "# Phase 21.17.1 JSON5/JSONC court — matrix"
    echo
    echo "| fixture | format | src len | out len | sha256 match | cmp | exact | decline rc | control rc |"
    echo "| --- | --- | ---: | ---: | --- | --- | --- | ---: | ---: |"
    # shellcheck disable=SC2162
    while IFS='	' read -r a b c d e g h i j k; do
        [ "$a" = "fixture" ] && continue
        [ -z "$a" ] && continue
        if [ "$d" = "$g" ]; then sh=true; else sh=false; fi
        echo "| \`$a\` | $b | $c | $e | $sh | $h | $i | $j | $k |"
    done < "$TSV"
} > "$CAMPAIGN/MATRIX.md"

# --- counts.txt -------------------------------------------------------------
{
    echo "fixtures $fixtures_n"
    echo "normal $normal_n"
    echo "exact_ok $exact_ok"
    echo "exact_fail $exact_fail"
    echo "surface_fail $surface_fail"
    echo "typed_declines_ok $declines_ok"
    echo "json_control_ok $json_ctl_ok"
    echo "opaque_controls_ok $opaque_ok"
    echo "opaque_controls $opaque_n"
    echo "binary $(sha256sum "$BIN" | cut -d' ' -f1)"
} > "$CAMPAIGN/counts.txt"

# --- environment.json -------------------------------------------------------
cat > "$CAMPAIGN/environment.json" <<EOF
{
  "campaign": "$CAMPAIGN",
  "phase": "21.17.1 — JSON5/JSONC structured-extra surface + exact closure",
  "utc": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "git_commit": "$(git rev-parse HEAD 2>/dev/null || echo unknown)",
  "git_dirty": "$(git status --porcelain | tr '\n' ' ' | sed 's/"/\\"/g')",
  "arch": "$(uname -m)",
  "service": "dev",
  "base_image": "rust:1.99.0-slim-bookworm@sha256:452176c0cefca88c0b3184ce85a4eb03e3d4fa05d2afb5366abcba853221019e",
  "rustc": "$(rustc --version)",
  "cargo": "$(cargo --version)",
  "cargo_lock_sha256": "$(sha256sum Cargo.lock | cut -d' ' -f1)",
  "bin": "$BIN",
  "bin_sha256": "$(sha256sum "$BIN" | cut -d' ' -f1)",
  "profile": "debug",
  "fixtures_tool": "tools/fixtures/make-json5.py (committed small fixtures); large.json5 regenerated with POSIX printf",
  "env_affecting_semantics": {"LC_ALL": "C"}
}
EOF

# --- receipt.json -----------------------------------------------------------
verdict="PASS"
if [ "$exact_fail" -ne 0 ] || [ "$surface_fail" -ne 0 ] \
    || [ "$declines_ok" -ne "$normal_n" ] || [ "$json_ctl_ok" -ne 1 ] \
    || [ "$opaque_ok" -ne "$opaque_n" ]; then
    verdict="FAIL"
fi
cat > "$CAMPAIGN/receipt.json" <<EOF
{
  "campaign": "$CAMPAIGN",
  "phase": "21.17.1 — JSON5/JSONC structured-extra surface + exact closure",
  "utc": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "measured_commit": "$(git rev-parse HEAD 2>/dev/null || echo unknown)",
  "tree_state": "$(git status --porcelain | tr '\n' ' ' | sed 's/"/\\"/g')",
  "service": "dev",
  "profile": "debug",
  "bin": "$BIN",
  "bin_sha256": "$(sha256sum "$BIN" | cut -d' ' -f1)",
  "base_image": "rust:1.99.0-slim-bookworm@sha256:452176c0cefca88c0b3184ce85a4eb03e3d4fa05d2afb5366abcba853221019e",
  "rustc": "$(rustc --version)",
  "cargo": "$(cargo --version)",
  "fixtures": "$ALL",
  "fixture_tool": "tools/fixtures/make-json5.py (small) + POSIX printf (large)",
  "invariant": "materialize(field) == source (length + SHA-256 + cmp) after source AND descriptor deletion",
  "observations": ["metadata", "text", "search-match", "native json5-pointer", "native json5-node", "native json5-find", "native json5-comments"],
  "surface": "comments (exact spans, never dropped), unquoted keys, single-quoted strings, trailing commas, hex/leading-dot/Infinity/NaN numbers, string continuations, extended whitespace, member order, duplicate keys, numeric/escape spelling, recorded dialect (jsonc vs json5)",
  "declines": "an out-of-range pointer declines typed (rc 6); the strict-JSON control stays Json and a native JSON5 selector on it declines typed; the malformed and prose controls stay Opaque and a common observation declines typed (rc 6), never a panic",
  "precedence": "JSON is tried first (a strict JSON document stays Json, never reclassified); JSON5/JSONC is tried immediately after JSON and before JSONL/YAML/TOML/CSV/Markdown/XML/HTML, because it requires at least one JSON5/JSONC-only construct and a JSON5 source (e.g. {a: 1}) would otherwise be wrongly claimed by YAML",
  "rc_codes": "0 ok; 6 unsupported-feature; 2 usage; 8 resource-limit; 31 invalid-json5-structure",
  "adr_0060": "the Json5Model node depends on the DocumentExact root (sha256(source)); no source-reading node aliases another field's source",
  "verdict": "$verdict"
}
EOF

cat > "$CAMPAIGN/commands.txt" <<'EOF'
docker compose run --rm --no-TTY dev sh tools/phase21-17-1-json5-court.sh
# inside the court:
#   cargo build --locked --all-features
#   target/debug/vole-document field-build FIXTURE --store STORE --voldoc F.voldoc
#   target/debug/vole-document observe --store STORE --field HEX (--metadata|--doc-text|--json5-pointer P|--json5-node ""|--json5-find PAT|--json5-comments) --kind metadata|text|structure|exact
#   rm source F.voldoc
#   target/debug/vole-document materialize --store STORE --field HEX --exact --output OUT ; cmp OUT source
# Full gate (dev service):
#   cargo fmt --all --check
#   cargo clippy --all-targets --all-features -- -D warnings
#   cargo test --locked --all-features
#   cargo test --locked
#   cargo test --locked --no-default-features
#   MSRV: docker compose run --rm --no-TTY msrv cargo build --locked --all-features
EOF

# --- SUMMARY.md -------------------------------------------------------------
{
    echo "# Phase 21.17.1 — JSON5 / JSONC (structured-extra Wave 2) court"
    echo
    echo "**Question.** Does the JSON5/JSONC format close exactly and expose a"
    echo "representation-preserving **superset** model (comments with exact spans,"
    echo "unquoted keys, single quotes, trailing commas, hex/leading-dot/Infinity/NaN"
    echo "numbers, string continuations, the extended whitespace set, member order,"
    echo "duplicate keys, numeric/escape spelling, and a recorded jsonc-vs-json5"
    echo "dialect) on top of the whole-source exact leaf — while keeping the"
    echo "strict-Json-vs-Json5 boundary and declining malformed/non-JSON inputs typed?"
    echo
    echo "**Method.** Each self-authored fixture is ingested via \`field-build\`,"
    echo "observed, then — after the **source file and the standalone descriptor are"
    echo "deleted** — rematerialized exactly in a fresh process and compared with"
    echo "\`length + SHA-256 + cmp\`. An out-of-range pointer is asked for and required"
    echo "to decline typed; the strict-JSON, malformed, and prose controls pin the"
    echo "detection boundaries. The court runs in the pinned \`dev\` service using only"
    echo "POSIX \`sh\`, coreutils, git, and the shipped binary (no python3, no jq)."
    echo
    echo "## Exactness (after source + descriptor deletion)"
    echo
    tail -n +3 "$CAMPAIGN/MATRIX.md"
    echo
    echo "## Counts"
    echo
    echo '```'
    cat "$CAMPAIGN/counts.txt"
    echo '```'
    echo
    echo "## Per-fixture observation files (raw/)"
    echo
    ls "$RAW" | sed 's/^/- `/; s/$/`/'
    echo
    echo "## Scope (honest)"
    echo
    echo "- **Shipped here:** byte-based conservative JSON5/JSONC detection (a strict"
    echo "  JSON source stays \`Json\`); the bounded JSON5 parser reusing the JSON"
    echo "  adapter's node arena and span policy; native"
    echo "  \`json5-pointer\`/\`json5-node\`/\`json5-find\`/\`json5-comments\`; common"
    echo "  \`metadata\`/\`text\`/\`search-match\`; a recorded dialect."
    echo "- **Precedence:** JSON first (strict JSON is never reclassified); JSON5/JSONC"
    echo "  immediately after JSON and before JSONL/YAML/TOML/CSV/Markdown/XML/HTML."
    echo "- **Declines:** a malformed source, an over-cap node/comment/string/depth/"
    echo "  document budget, and an out-of-range pointer are typed declines; such input"
    echo "  stays \`Opaque\`."
    echo "- **Exactness** is the whole source (a RAW-like \`DocumentExact\`): the JSON5"
    echo "  model is derived (\`Q_gen\`) and never on the exactness path (ADR-0060: the"
    echo "  model node depends on the \`sha256(source)\` root)."
    echo "- **IdentifierName:** the exact ECMAScript/Unicode ID_Start/ID_Continue tables"
    echo "  are approximated with \`char::is_alphabetic\`/\`is_alphanumeric\` (a bounded,"
    echo "  deterministic, no-dependency approximation), not a byte-exact port."
    echo "- **Not claimed here:** the economic court (separate script)."
    echo "- **Never run on the host:** every command above ran in the pinned \`dev\`"
    echo "  container."
} > "$CAMPAIGN/SUMMARY.md"

echo
if [ "$verdict" != "PASS" ]; then
    echo "PHASE 21.17.1 JSON5 COURT: FAIL — campaign $CAMPAIGN (exact_fail=$exact_fail surface_fail=$surface_fail declines_ok=$declines_ok json_ctl_ok=$json_ctl_ok opaque_ok=$opaque_ok)" >&2
    exit 1
fi
echo "PHASE 21.17.1 JSON5 COURT: PASS — campaign $CAMPAIGN"
