#!/bin/sh
# Phase-12.13 security court — hostile-input safety over the ingest/observe path.
#
# Runs inside a pinned, memory-capped service (doc-baseline: 6 g, no swap). For
# **every** fixture in the committed hostile corpus it:
#
#   encode --force raw FIXTURE F.voldoc         # exact opaque descriptor
#   decode F.voldoc OUT && cmp OUT FIXTURE      # the opaque floor is exact
#   capabilities FIXTURE                        # detection never panics
#   field-ingest F.voldoc --store STORE         # the universal ingest path
#   observe --metadata / --doc-text             # materialize the derived models
#   find / materialize --exact                  # query + exact closure
#
# and asserts the universal invariants (research I §8):
#   1. never panic;
#   2. never build a filesystem path from a member name (canary escaped?);
#   3. never fetch the network (strace: no connect);
#   4. never execute script / an external process (strace: no foreign execve);
#   5. never exceed configured bounds uncontrollably (timeout; bounded RSS);
#   6. every failure is a typed error, never InternalInvariant;
#   7. for every preserved case, materialize --exact == original (cmp).
#
# Per fixture it records the outcome class (reject vs opaque-preserve-and-decline
# vs accept), the error code, and the exactness result.
#
# The corpus is generated by tools/fixtures/phase12-hostile-gen.py (stdlib only)
# and committed under tests/fixtures/phase12-hostile/. The court regenerates it
# and asserts byte-for-byte determinism before running.
#
# Usage (from the host):
#   docker compose run --rm --no-TTY doc-baseline sh tools/phase12-security-court.sh
set -u

cd /work
LC_ALL=C
export LC_ALL
umask 022

DATE="$(date -u +%Y-%m-%d)"
SHA="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
CAMPAIGN="${1:-evidence/campaigns/${DATE}-phase12-security-${SHA}}"
COMMITTED="tests/fixtures/phase12-hostile"
GEN="$CAMPAIGN/raw/regenerated"
WORK="$CAMPAIGN/raw/work"
B="${VOLE_BIN:-./target/debug/vole-document}"
PER_FIXTURE_TIMEOUT="${PER_FIXTURE_TIMEOUT:-60}"

rm -rf "$CAMPAIGN"
mkdir -p "$CAMPAIGN/raw" "$WORK" "$GEN"

echo "== Phase 12.13 security court =="
echo "campaign: $CAMPAIGN"

# ---------------------------------------------------------------------------
# 0. Regenerate the corpus and prove it is byte-identical to the committed one.
# ---------------------------------------------------------------------------
python3 tools/fixtures/phase12-hostile-gen.py "$GEN" >/dev/null
if diff -r "$COMMITTED" "$GEN" > "$CAMPAIGN/raw/determinism.diff" 2>&1; then
  DETERMINISM=ok
else
  DETERMINISM=DIFFER
fi
echo "corpus determinism: $DETERMINISM"

# ---------------------------------------------------------------------------
# 1. Build the all-features binary (the field verbs + all format adapters).
# ---------------------------------------------------------------------------
cargo build --quiet --locked --all-features 2> "$CAMPAIGN/raw/build.log"

ASSERT="$CAMPAIGN/raw/assertions.tsv"
OUT="$CAMPAIGN/raw/outcomes.tsv"
: > "$ASSERT"
printf 'fixture\tcategory\texpect\toutcome\tclass\tingest_exit\tobserve_exit\texact\tnet\tsubproc\trss_kb\twall_ms\n' > "$OUT"

TOTAL=0; PASS=0; FAIL=0
record() {
  TOTAL=$((TOTAL + 1))
  if [ "$1" = PASS ]; then PASS=$((PASS + 1)); else FAIL=$((FAIL + 1)); fi
  printf '%s\t%s\t%s\n' "$1" "$2" "$3" >> "$ASSERT"
}
assert_eq() { if [ "$2" = "$3" ]; then record PASS "$1" "$3"; else record FAIL "$1" "expected[$2] got[$3]"; fi; }

# Classic rejection classes (byte authority / identity broken) vs decode declines.
is_reject_class() {
  case "$1" in
    InvalidZipStructure|InvalidXmlStructure|InvalidPackageStructure|CoverageViolation|ResourceLimit|IntegrityMismatch) return 0 ;;
    *) return 1 ;;
  esac
}

# A canary outside the working tree; a member-name traversal must never touch it.
CANARY_DIR="$WORK/canary"
mkdir -p "$CANARY_DIR"
printf 'CANARY-DO-NOT-TOUCH\n' > "$CANARY_DIR/passwd"
printf 'CANARY-DO-NOT-TOUCH\n' > "$WORK/escaped"
CANARY_SHA="$(sha256sum "$CANARY_DIR/passwd" | cut -d' ' -f1)"

# First probe that returns a typed error determines the recorded class.
FIRST_CLASS=""
FIRST_EXIT=0
probe() {
  # $1 = label, rest = command; captures stderr, records the first typed error.
  "$@" > "$WORK/probe.out" 2> "$WORK/probe.err"
  rc=$?
  if [ "$rc" -ne 0 ] && [ -z "$FIRST_CLASS" ]; then
    cls=$(sed -n 's/^error: \([A-Za-z]*\):.*/\1/p' "$WORK/probe.err" | head -1)
    FIRST_CLASS="${cls:-Unknown}"
    FIRST_EXIT=$rc
  fi
  return $rc
}

# Parse the manifest (category + expect) with python3 (stdlib only).
python3 - "$COMMITTED/manifest.json" > "$CAMPAIGN/raw/manifest.tsv" <<'PY'
import json, sys
m = json.load(open(sys.argv[1]))
for name in sorted(m["fixtures"]):
    f = m["fixtures"][name]
    print(f"{name}\t{f['category']}\t{f['expect']}")
PY

while IFS="$(printf '\t')" read -r name category expect; do
  [ -z "$name" ] && continue
  fixture="$COMMITTED/$name"
  sandbox="$WORK/fx/$name"
  rm -rf "$sandbox"
  mkdir -p "$sandbox"

  # --- opaque floor: encode + decode + cmp (must always be exact) -----------
  "$B" encode --force raw "$fixture" "$sandbox/src.voldoc" > "$sandbox/encode.json" 2> "$sandbox/encode.err"
  encode_rc=$?
  "$B" decode "$sandbox/src.voldoc" "$sandbox/roundtrip" > /dev/null 2> "$sandbox/decode.err"
  decode_rc=$?
  exact=no
  if [ "$encode_rc" -eq 0 ] && [ "$decode_rc" -eq 0 ] && cmp -s "$sandbox/roundtrip" "$fixture"; then
    exact=yes
  fi

  # --- detection never panics ----------------------------------------------
  "$B" capabilities "$fixture" > "$sandbox/caps.json" 2> "$sandbox/caps.err"
  caps_rc=$?

  # --- ingest under strace (network + process) and /usr/bin/time (RSS) ------
  FIRST_CLASS=""; FIRST_EXIT=0
  ingest_log="$sandbox/net.strace"
  /usr/bin/time -v -o "$sandbox/time.txt" \
    timeout "$PER_FIXTURE_TIMEOUT" \
    strace -f -e trace=network,process -o "$ingest_log" \
    "$B" field-ingest "$sandbox/src.voldoc" --store "$sandbox/store" \
    > "$sandbox/ingest.json" 2> "$sandbox/ingest.err"
  ingest_rc=$?
  field=$(sed -n 's/.*"field":"\([0-9a-f]*\)".*/\1/p' "$sandbox/ingest.json" | head -1)

  net="clean"; [ -s "$ingest_log" ] && grep -q 'connect(' "$ingest_log" && net="NETWORK"
  subproc="clean"
  if [ -s "$ingest_log" ]; then
    if grep -E 'execve\(' "$ingest_log" | grep -vE 'vole-document|/usr/bin/time|timeout' | grep -qE 'execve\('; then
      subproc="FOREIGN-EXECVE"
    fi
  fi
  rss_kb=$(sed -n 's/.*Maximum resident set size (kbytes): \([0-9]*\).*/\1/p' "$sandbox/time.txt" | head -1)
  [ -z "$rss_kb" ] && rss_kb=0

  # timeout wrapper exits 124 on a hang.
  timed_out=no
  [ "$ingest_rc" -eq 124 ] && timed_out=yes

  # --- derived-model observations (metadata, then text) ---------------------
  obs_exit=0
  if [ "$ingest_rc" -eq 0 ] && [ -n "$field" ]; then
    probe "$B" observe --store "$sandbox/store" --field "$field" --metadata --kind metadata
    probe "$B" observe --store "$sandbox/store" --field "$field" --doc-text --kind text
    probe "$B" find --store "$sandbox/store" --field "$field" --text XF
    obs_exit=$FIRST_EXIT
  fi

  # --- exact closure through the field --------------------------------------
  field_exact=skip
  if [ "$ingest_rc" -eq 0 ] && [ -n "$field" ]; then
    "$B" materialize --store "$sandbox/store" --field "$field" --exact \
      --output "$sandbox/out.bin" > /dev/null 2> "$sandbox/mat.err"
    if [ $? -eq 0 ] && cmp -s "$sandbox/out.bin" "$fixture"; then field_exact=yes; else field_exact=no; fi
  fi

  # --- classify -------------------------------------------------------------
  outcome="accept"
  cls="-"
  if [ "$ingest_rc" -ne 0 ]; then
    cls=$(sed -n 's/^error: \([A-Za-z]*\):.*/\1/p' "$sandbox/ingest.err" | head -1)
    [ -z "$cls" ] && cls=Unknown
    if is_reject_class "$cls"; then outcome="reject"; else outcome="ingest-decline"; fi
  elif [ -n "$FIRST_CLASS" ]; then
    cls="$FIRST_CLASS"
    if is_reject_class "$cls"; then outcome="reject"; else outcome="opaque-preserve-and-decline"; fi
  fi

  # --- universal invariants (hard gates) ------------------------------------
  panic=no
  grep -rl 'panicked at' "$sandbox" >/dev/null 2>&1 && panic=yes

  canary_ok=yes
  [ "$(sha256sum "$CANARY_DIR/passwd" | cut -d' ' -f1)" = "$CANARY_SHA" ] || canary_ok=no

  if [ "$panic" = yes ]; then record FAIL "$name.no_panic" "panicked"; else record PASS "$name.no_panic" "clean"; fi
  if [ "$timed_out" = yes ]; then record FAIL "$name.no_hang" "timeout"; else record PASS "$name.no_hang" "bounded"; fi
  if [ "$net" = clean ]; then record PASS "$name.no_network" "clean"; else record FAIL "$name.no_network" "$net"; fi
  if [ "$subproc" = clean ]; then record PASS "$name.no_subprocess" "clean"; else record FAIL "$name.no_subprocess" "$subproc"; fi
  if [ "$canary_ok" = yes ]; then record PASS "$name.no_path_escape" "canary-intact"; else record FAIL "$name.no_path_escape" "canary-modified"; fi
  if [ "$caps_rc" -ne 0 ]; then record FAIL "$name.capabilities" "exit $caps_rc"; fi
  if [ "$exact" = yes ]; then record PASS "$name.opaque_exact" "yes"; else record FAIL "$name.opaque_exact" "no (encode=$encode_rc decode=$decode_rc)"; fi
  if [ "$field_exact" = no ]; then record FAIL "$name.field_exact" "no"; fi
  if [ "$cls" = InternalInvariant ]; then record FAIL "$name.typed_error" "InternalInvariant"; fi

  # --- research-derived coarse disposition (falsifiable prediction) ---------
  case "$expect" in
    reject)
      if [ "$outcome" = reject ]; then record PASS "$name.expect_reject" "$cls"; else record FAIL "$name.expect_reject" "outcome=$outcome"; fi
      ;;
    accept)
      if [ "$outcome" = accept ]; then record PASS "$name.expect_accept" "accept"; else record FAIL "$name.expect_accept" "outcome=$outcome cls=$cls"; fi
      ;;
    preserve|decline)
      # A decline prediction requires that no *hard* invariant broke and the bytes
      # stayed exact; the observation may accept or decline, typed.
      case "$outcome" in
        opaque-preserve-and-decline|ingest-decline)
          record PASS "$name.expect_decline" "$outcome" ;;
        accept)
          record PASS "$name.expect_decline" "accept" ;;
        *)
          record FAIL "$name.expect_decline" "outcome=$outcome" ;;
      esac
      ;;
  esac

  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$name" "$category" "$expect" "$outcome" "$cls" "$ingest_rc" "$obs_exit" \
    "$field_exact" "$net" "$subproc" "$rss_kb" "-" >> "$OUT"
  echo "  $name: $outcome ($cls) exact=$field_exact net=$net rss=${rss_kb}kB"
done < "$CAMPAIGN/raw/manifest.tsv"

# ---------------------------------------------------------------------------
# Environment / provenance.
# ---------------------------------------------------------------------------
RUSTC=$(rustc -vV | sed -n 's/^release: //p')
CARGO=$(cargo -V | sed -n 's/^cargo //p')
LOCK_SHA=$(sha256sum Cargo.lock | cut -d' ' -f1)
ARCH=$(uname -m)
COMMIT=$(git rev-parse HEAD 2>/dev/null || echo unknown)
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)
DIRTY=$(git status --porcelain 2>/dev/null | tr '\n' ';')
RUN_UTC=$(date -u +%Y-%m-%dT%H:%M:%SZ)
BASE=$(sed -n 's/^ARG BASE_STABLE=//p' Dockerfile)

cat > "$CAMPAIGN/environment.json" <<EOF
{
  "campaign": "$(basename "$CAMPAIGN")",
  "run_utc": "$RUN_UTC",
  "arch": "$ARCH",
  "git_branch": "$BRANCH",
  "git_commit": "$COMMIT",
  "git_dirty": "$DIRTY",
  "cargo_lock_sha256": "$LOCK_SHA",
  "court_image": "vole-document/doc-baseline:1.99.0",
  "base_image": "$BASE",
  "rustc": "$RUSTC",
  "cargo": "$CARGO",
  "corpus_generator": "tools/fixtures/phase12-hostile-gen.py",
  "corpus_determinism": "$DETERMINISM",
  "per_fixture_timeout_s": $PER_FIXTURE_TIMEOUT,
  "features_under_test": "all-features (field, package, opc, docx, epub, xml, ...)",
  "env_vars_affecting_semantics": { "LC_ALL": "C", "CARGO_TERM_COLOR": "never" },
  "notes": "Each fixture is a tiny locally-generated hostile input (no third-party document bytes). field-ingest + observe run under strace -f (network,process) and a wall-clock timeout; a canary file outside the working tree is checked for path-escape; every failure class is parsed from stderr and required to be typed."
}
EOF

cat > "$CAMPAIGN/commands.txt" <<EOF
# Phase 12.13 security court — exact commands
# Commit under test: $COMMIT (branch $BRANCH); dirty: $DIRTY
# Run (UTC): $RUN_UTC   Base image (ARG BASE_STABLE): $BASE
# Service: vole-document/doc-baseline:1.99.0 (mem 6g == memswap; pids 4096; cpus 8)
# rustc $RUSTC, cargo $CARGO, arch $ARCH; Cargo.lock sha256: $LOCK_SHA

# 0) determinism + 1) build
python3 tools/fixtures/phase12-hostile-gen.py <REGEN>   # diff -r == committed corpus
cargo build --locked --all-features

# 2) per fixture FIXTURE in tests/fixtures/phase12-hostile/:
#   vole-document encode --force raw FIXTURE src.voldoc
#   vole-document decode src.voldoc roundtrip && cmp roundtrip FIXTURE
#   vole-document capabilities FIXTURE
#   /usr/bin/time -v timeout 60 strace -f -e trace=network,process \\
#       vole-document field-ingest src.voldoc --store store
#   vole-document observe --store store --field F --metadata --kind metadata
#   vole-document observe --store store --field F --doc-text --kind text
#   vole-document find    --store store --field F --text XF
#   vole-document materialize --store store --field F --exact --output out.bin
#   cmp out.bin FIXTURE
EOF

# --- summary -----------------------------------------------------------------
{
  echo "# Phase 12.13 — security + hostile-input court"
  echo
  echo "**Result: $PASS/$TOTAL assertions passed, $FAIL failed.** Corpus determinism: **$DETERMINISM**."
  echo
  echo "Every fixture in the committed hostile corpus (\`$COMMITTED\`) was pushed through"
  echo "the universal ingest/observe path inside the capped \`doc-baseline\` service. The"
  echo "court asserts: never panic; never fetch the network (strace); never spawn a"
  echo "foreign process (strace); never touch a canary file outside the tree (no"
  echo "member-name path escape); a typed error, never \`InternalInvariant\`; and"
  echo "\`materialize --exact == original\` for every preserved case."
  echo
  echo '| fixture | category | predict | observed | class | exact |'
  echo '|---|---|---|---|---|---|'
  awk -F'\t' 'NR>1 { printf "| %s | %s | %s | %s | %s | %s |\n", $1,$2,$3,$4,$5,$8 }' "$OUT"
  echo
  echo "## Outcome-class tally"
  echo
  echo '```'
  awk -F'\t' 'NR>1 { c[$4]++ } END { for (k in c) printf "%-32s %d\n", k, c[k] }' "$OUT" | sort
  echo '```'
  echo
  echo "## Universal invariants"
  echo
  echo '```'
  awk -F'\t' '{ printf "%-5s %-34s %s\n", $1, $2, $3 }' "$ASSERT" \
    | grep -E 'no_panic|no_hang|no_network|no_subprocess|no_path_escape|opaque_exact|typed_error' \
    | sort | uniq -c | sed 's/^ *//'
  echo '```'
  echo
  echo "## Failing assertions (if any)"
  echo
  if [ "$FAIL" -eq 0 ]; then
    echo "_none_"
  else
    echo '```'
    grep -P '^FAIL' "$ASSERT" || true
    echo '```'
  fi
  echo
  echo "The library half of this court is \`tests/phase12_security.rs\` (typed"
  echo "rejection of the structural/list threats under \`Limits::STRICT\` and"
  echo "\`DEFAULT\`, plus XML hardening); the fuzz half is the 18-target campaign."
  echo
  echo "---"
  echo
  echo "## Environment (receipt)"
  echo
  echo "- Commit under test: \`$COMMIT\` (branch \`$BRANCH\`), dirty files: \`$DIRTY\`"
  echo "- Service: \`vole-document/doc-baseline:1.99.0\`; base \`$BASE\`"
  echo "- Toolchain: rustc \`$RUSTC\`, cargo \`$CARGO\`, arch \`$ARCH\`"
  echo "- \`Cargo.lock\` sha256: \`$LOCK_SHA\`"
  echo "- Run (UTC): $RUN_UTC"
} > "$CAMPAIGN/SUMMARY.md"

cp "$OUT" "$CAMPAIGN/outcomes.tsv"
( cd "$CAMPAIGN" && find raw -type f | sort | xargs sha256sum > raw.sha256 ) 2>/dev/null || true

echo "assertions: $PASS/$TOTAL passed, $FAIL failed"
echo "wrote $CAMPAIGN"
[ "$FAIL" -eq 0 ] || exit 1
