#!/bin/sh
# Phase-12.14 — seal a receipt for the flagship demo (`tools/phase12-demo.sh`).
#
# Runs the reproducible demo at the current HEAD inside the pinned, capped
# `doc-baseline` service, captures its **live** stdout (no recorded or fabricated
# numbers), and copies the small JSON artifacts it wrote into the sealed receipt.
# The receipt records the actual HEAD commit and the honest caveat that the
# `capabilities` step runs on the sealed oracle copy (kept for detection + `cmp`)
# after the runtime sources and descriptors were deleted.
#
# Usage (from the host; runs inside the pinned service):
#   docker compose run --rm --no-TTY doc-baseline sh tools/phase12-demo-receipt.sh
set -u

cd /work
LC_ALL=C
export LC_ALL

SHA="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
CAMPAIGN="${1:-evidence/campaigns/$(date -u +%Y-%m-%d)-phase12-demo-${SHA}}"

# Snapshot provenance *before* this script creates its own receipt directory.
COMMIT=$(git rev-parse HEAD 2>/dev/null || echo unknown)
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)
DIRTY=$(git status --porcelain 2>/dev/null | head -40 | tr '\n' ';' || echo unknown)
RUN_UTC=$(date -u +%Y-%m-%dT%H:%M:%SZ)
RUSTC=$(rustc -vV | sed -n 's/^release: //p')
CARGO=$(cargo -V | sed -n 's/^cargo //p')
LOCK_SHA=$(sha256sum Cargo.lock | cut -d' ' -f1)
ARCH=$(uname -m)
BASE_STABLE=$(sed -n 's/^ARG BASE_STABLE=//p' Dockerfile)
JQ=$(jq --version)

rm -rf "$CAMPAIGN"
mkdir -p "$CAMPAIGN/raw"

# Run the demo, capturing stdout and the exit code verbatim.
set +e
sh tools/phase12-demo.sh > "$CAMPAIGN/raw/demo.stdout.txt" 2> "$CAMPAIGN/raw/demo.stderr.txt"
RC=$?
set -e
printf '%s\n' "$RC" > "$CAMPAIGN/raw/demo.exitcode"

# Copy the small live JSON artifacts (never the store / source / oracle bytes).
W=evidence/scratch/phase12-demo
find "$W" -maxdepth 1 -name '*.json' -exec cp {} "$CAMPAIGN/raw/" \; 2>/dev/null || true
find "$W" -maxdepth 1 -type f ! -name '*.json' -size -100k -exec cp {} "$CAMPAIGN/raw/" \; 2>/dev/null || true

cat > "$CAMPAIGN/environment.json" <<EOF
{
  "campaign": "$(basename "$CAMPAIGN")",
  "run_utc": "$RUN_UTC",
  "arch": "$ARCH",
  "git_branch": "$BRANCH",
  "git_commit": "$COMMIT",
  "git_dirty": "$DIRTY",
  "cargo_lock_sha256": "$LOCK_SHA",
  "doc_baseline": {
    "service_image": "vole-document/doc-baseline:1.99.0",
    "base_image": "$BASE_STABLE",
    "rustc": "$RUSTC",
    "cargo": "$CARGO",
    "jq": "$JQ"
  },
  "demo_exit_code": $RC,
  "commands": "sh tools/phase12-demo.sh",
  "caveat": "The capabilities step runs on the sealed oracle copy under evidence/scratch/phase12-demo/oracle, kept for format detection and cmp after the runtime sources and descriptors were deleted; the store never references the oracle copy (same design as the 12.10 removal court).",
  "env_vars_affecting_semantics": { "CARGO_TERM_COLOR": "never", "LC_ALL": "C" }
}
EOF

cat > "$CAMPAIGN/commands.txt" <<EOF
# Phase-12.14 flagship demo receipt — exact commands
# Commit under test: $COMMIT (branch $BRANCH); dirty: $DIRTY
# Run (UTC): $RUN_UTC
# Service image: vole-document/doc-baseline:1.99.0; base $BASE_STABLE
# rustc $RUSTC, cargo $CARGO, jq $JQ, arch $ARCH
# Cargo.lock sha256: $LOCK_SHA
# All commands run inside the pinned, capped doc-baseline image; nothing on the host.

docker compose run --rm --no-TTY doc-baseline sh tools/phase12-demo-receipt.sh

# Inside phase12-demo-receipt.sh:
#   sh tools/phase12-demo.sh     > CAMPAIGN/raw/demo.stdout.txt
# The demo runs (all inside doc-baseline):
#   python3 tools/fixtures/doc-triplet-gen.py ORACLE
#   vole-document encode --force raw; field-ingest (report.pdf/.docx/.epub)
#   rm the runtime sources + descriptors
#   capabilities / find / observe / explain --analyze / materialize --exact
EOF

{
  echo "# Phase 12.14 — flagship demo receipt"
  echo
  echo "Generated by \`tools/phase12-demo-receipt.sh\` (which runs \`tools/phase12-demo.sh\`)"
  echo "inside the pinned, capped \`doc-baseline\` service. Every number below is the demo's"
  echo "**live** output (\`raw/demo.stdout.txt\`), not re-typed."
  echo
  echo "Commit under test: \`$COMMIT\` (branch \`$BRANCH\`, dirty: \`$DIRTY\`) · run (UTC) $RUN_UTC.  "
  echo "Service image \`vole-document/doc-baseline:1.99.0\`, base \`$BASE_STABLE\`.  "
  echo "rustc \`$RUSTC\`, cargo \`$CARGO\`; Cargo.lock sha256 \`$LOCK_SHA\`; arch \`$ARCH\`."
  echo
  echo "Demo exit code: \`$RC\`."
  echo
  echo "## Live demo output"
  echo
  echo '```text'
  cat "$CAMPAIGN/raw/demo.stdout.txt"
  echo '```'
  echo
  echo "## Honest caveat"
  echo
  echo "The \`capabilities\` step runs on the sealed **oracle** copy under"
  echo "\`evidence/scratch/phase12-demo/oracle\` (kept for format detection and \`cmp\`),"
  echo "after the runtime sources and their ingest descriptors were deleted. The store"
  echo "never references that oracle copy; it is the same design as the 12.10 removal"
  echo "court. \`find\`, \`observe\`, \`explain --analyze\` and \`materialize --exact\` all run"
  echo "against the field store with the runtime source gone."
} > "$CAMPAIGN/SUMMARY.md"

( cd "$CAMPAIGN" && sha256sum SUMMARY.md commands.txt environment.json raw/* > raw.sha256 ) 2>/dev/null || true

echo "wrote $CAMPAIGN (exit $RC)"
